### ISSUE TITLE
Feature Request: Be able to constrain in-memory usage

### ISSUE THREAD

**Issue by jdnurmi** [blevesearch/bleve#1007]
Weird use case, but potentially useful feature request:

I'm making use of Bleve as an index for various information within a persistent daemon, but the index is not "typically" being updated or searched actively as the triggering events are relatively rare.

To be clear - it works great!

But because of my indexing patterns being burst-write and occasional-search, I find myself with a very large in-memory index (seems to be stuff in vellum.* from pprof, but I can get you more details if needed).

As a workaround, I have my daemon periodically close the index when idle and reopen it on demand (which seems to force the memory to be released and returned - so this isn't a leak per se), but for both performance and predictability reasons, it'd be nice to be able to set constraints for the amount of the index retained in memory.

If it helps, I'm using scorch with a lightly customized tokenizer/mapper, but I suspect the same desire would exist for other local backends.

**Comment by mschoch** [comment]
It's not a weird use case at all, in fact it's one of the things we've spent a LOT of time working on at Couchbase in our use of Bleve there.  As it sounds like you're already aware, this is not trivial in a real Go application, but the good news is that since we've been working on the same thing, hopefully some of the hooks we put into place will help you as well.

The first thing to clear up is how the memory is being used.  You mentioned using scorch, which will use mmap to make all the index data stored on disk available in memory (without actually loading it all at once).  I mention this only because depending on which memory stats you're looking at, sometimes this is included and sometimes it isn't.  At the highest level, you probably want to ignore this memory, since in theory if your application actually needs the memory for something else, the operating system should page out the least recently used bleve index data.

Second, the memory you probably want to focus on is the Go heap.  Although much of the index data is loaded via mmap, there are of course support structures which are allocated on the heap, and there are data structures needed for the indexing and querying processes which also use the heap.  So, it's helpful to break this down into those 3 pieces:

First, memory used by the indexing process itself.  The theory here is that this is if we stop indexing, this should eventually go back to 0.  So, if we are using too much memory, one thing we can do is stop/pause indexing.  To do this we use a callback in scorch, which fires for key events.  Setting this up is a bit weird in bleve because our configuration data is persisted, but callback functions are ephemeral at runtime, so we use a registry with string identifiers.  You can see how this is processed here:

https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L113

And you can see how an application uses it by registering a name/callback here:

https://github.com/couchbase/cbft/blob/1bcec5832c6d1ad1e73a83acc5be3f548479a4a0/cmd/cbft/init_bleve.go#L81

And configuring bleve to use it here:

https://github.com/couchbase/cbft/blob/a33ad7b7000a9d8d237ba273c47cc100401a0fb0/pindex_bleve.go#L526

So, how does this callback function work?  Basically there is an event fired at the start of every batch that is about to be indexed.  Inside this event, we can check how much memory bleve is using (more on this later) and if necessary block at this point.  How long should we block? Fortunately, there are other scorch events which can tell us when the index persister has made progress (wrote data to disk) which is a useful signal that we may be using less memory now and should check again.

How do we know much memory Bleve is using?  It's a tedious job, but we have code which attempts to estimate this.  The scorch index has a method called MemoryUsed() which does it's best to estimate this:

https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L551

Second, when querying the index, memory is also required.  Estimating this can be tricky as well, but we've taken the approach that even a coarse-grained estimate is better than nothing.  Things like the number of items you've requested (size-skip) end up being a reasonable proxy for how much memory we'll need (this totally ignores things like facets which may require unknown amounts of memory ahead of time).   Controlling memory used by querying also uses a callback, but it isn't configured at the index level, instead it is passed in with the Context object passed to the bleve SearchInContext() method.  By registering methods in the context object with the correct key, they will be invoked before and after the query is executed:

https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/index_impl.go#L53-L57

Notice that the signature for these methods passes an integer, which is our estimate for how much memory we think the query will need.  The impl for that if you are curious is here:

https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/index_impl.go#L392

So, the basic idea here is that before executing a query, you have some idea of how expensive it will be, you can choose to reject it by returning an error from the start query callback.  Second, assuming you accept it, you may want to do some accounting with that number.  That is why there is a corresponding query finished callback, so you can subtract that number back out of any accounting you were doing.  If you want to see how cbft actually implements these, you can see that here:

https://github.com/couchbase/cbft/blob/master/cmd/cbft/app_herder.go#L259-L328

Finally, the 3rd major piece of memory on the heap are the data-structures required to simply keep in the index open.  For this, the thinking is that there is nothing you can do except try to make them as small as possible.  This mostly consists of things like pointers to the segments themselves, inside each segment, the pointers to the mmap'd data.  However, it can also include some "materialized data" that we pull out of the mmap'd segments.  For example, inside each segment, there is a bi-directional mapping from field names to field identifiers (int), because this is small and frequently used, we put it into a map on the heap.  As I said, in general we try to keep this as small as possible, but it's possible that there are further improvements to be made here, and that people might want to make different trade-offs in the future.

I hope this helps at least start the conversation, and see if the hooks we've already put into place can help out with your use case.

CC @steveyen @abhinavdangeti  @sreekanth-cb

**Comment by jdnurmi** [comment]
Brilliant - it took me a few times through to parse / grok everything in here, but now I've got it performing just the way I want, thanks so much for the detailed response!
