### ISSUE TITLE
Provide example on how to force a manual merge to flatten an index

### ISSUE THREAD

**Issue by fproulx-eoscanada** [blevesearch/bleve#1052]
Hi Blevers,

First of all thank you for this amazing library.

We've been experimenting with Bleve to index large amount of data (we don't need to store it, we have an efficient raw storage), we create small documents with attributes to do conjunctive searches. We have on the order of 1 million document per hour, each with about a dozen attributes to index on.

We index by batches covering about 1 hour worth of documents and in some cases we get 20 GB index on disk, other hours may be much much smaller. Anyhow, once we close an hour-worth index, we re-open in read-only and offer for search. 

I would appreciate some guidance on merging those, or at least force optimizing a given range (for instance it seems excessive to have 600 zap files, the vast majority being less than 50 KB, other being like 8 GB)

Also, it appears that when opening such large index there is a lag (dozens of seconds) before the first query returns, after it is warmed up it's much much faster (microseconds) to do the same or similar, but not identical queries. Any advice on improving the cold start without necessarily issuing a bogus test query.

I have tried to setup a custom `scorchMergePlanOptions` when opening the index, but even though I confirmed that it loaded and validated it it does not perform any further merging (I'm doing that on the read-only, immutable index).  Do you have any recommendation of `scorchMergePlanOptions` values. We can trade off using more memory and/or disk during indexing, as long as the final index (immutable for read-only use) is fast and compact.

Thanks for your hard work,

**Comment by sreekanth-cb** [comment]
Hi @fproulx-eoscanada ,

To answer this query, there are many areas to touch upon. Not sure how effective I will be able to cover that.
Let me start with the number of files wrinkle,

During indexing, the number of files on disk is controlled by the merge policy as you 
figured out already. There are a few test cases which verifies the number of files expected for a 
given number of documents. 
You may refer here: https://github.com/blevesearch/bleve/blob/scorch/index/scorch/mergeplan/merge_plan_test.go

If you play around with that test to feed it with the number of documents at hand, 
you should be able to find the expected number of files on disk for a given number of documents, once the
indexing is complete.

For eg: 1 M document will result in 24 files on disk.


From a higher level, the persister routine in the system keeps writing segment files to disk and the merger keep merging those files to lesser number of compact and bigger files. 
And the current progress of those routines can be tracked over the stats like LastPersistedEpoch Vs LastMergedEpoch. 
The bigger the difference between those two stats, the higher would be number of files on disk 
than that is defined by the merge policy. Usually once the indexing is over, the merger will slowly catch up with the persister to result in ideal number of files on disk.

As you mentioned that, bleve isn't used as the primary data store in your case,
there is another possibility here.

Bleve has an option of unsafeBatch as here: 
https://github.com/blevesearch/bleve/blob/695c0fd368f8d0a5eaeb3400b06c7cce78ef2a70/index/scorch/scorch.go#L52

This would let the batch execute calls to return before the persistence of the data. Certainly this batch data would be searchable, just that its not yet made to the disk.

You could parameterise this:
https://github.com/blevesearch/bleve/blob/695c0fd368f8d0a5eaeb3400b06c7cce78ef2a70/index/scorch/scorch.go#L111

This option gives scorch more opportunity to perform in memory merging of segments/(batches) and would result in lesser number of files getting introduced to disk. 

And you may also tune these two options here
https://github.com/blevesearch/bleve/blob/695c0fd368f8d0a5eaeb3400b06c7cce78ef2a70/index/scorch/persister.go#L50
https://github.com/blevesearch/bleve/blob/695c0fd368f8d0a5eaeb3400b06c7cce78ef2a70/index/scorch/persister.go#L60

to control the persister merger dancing better to control the overall system behaviour. ;-) 
(You may experiment with these configs even in the default safe batch mode as well)


But the above mentioned unsafeBatch option inherently has higher memory requirement and you may just start stressing your system in that direction. (RAM).  This demands the application to control the indexing flow/batch execution depending on the memory usage of bleve.

The theory here is that, if we stop/pause indexing, then all the already indexed (non persisted) memory segments will go to disk and memory will become available for further indexing. 
So, if bleve/scorch is using too much memory, one thing we can do is stop/pause indexing from application's side.

To do this we can use a callback in scorch, which fires for key events. Setting this up is a bit weird in bleve because our configuration data is persisted, but callback functions are ephemeral at runtime, so we use a registry with string identifiers. 

You can see how this is processed here:
https://github.com/blevesearch/bleve/blob/master/index/scorch/scorch.go#L113

And you can see how an application uses it by registering a name/callback here:
https://github.com/couchbase/cbft/blob/1bcec5832c6d1ad1e73a83acc5be3f548479a4a0/cmd/cbft/init_bleve.go#L81

And configuring bleve to use it here:
https://github.com/couchbase/cbft/blob/a33ad7b7000a9d8d237ba273c47cc100401a0fb0/pindex_bleve.go#L526

So, how does this callback function work? Basically there is an event fired at the start of every batch that is about to be indexed.  Inside this event, we can check how much memory bleve is using and if necessary block at this point. 
How long should we block? Fortunately, there are other scorch events which can tell us when the index persister has made progress (wrote data to disk) which is a useful signal that we may be using less memory now and should check again.

How do we know much memory Bleve is using? It's a tedious job to count this manually. One option is start accounting the heap usage from Go runtime. You may play around with the Go runtime stats to figure this out.
And if you are interested in exploring this option further, please check the above cbft package which follows the unsafeBatch approach and all the above mentioned indexing flow controls based on bleve callbacks.

-Once the number of files are within the defined range, I guess the cold start problem should also alleviate?

-There are no other direct manual way to merge/compact the already existing zap files on disk.

-Playing around with the size of batches also helps in certain cases. Whats the average batch (no of documents) in your case.

cheers!

**Comment by abourget** [comment]
Right now, to force a merge, I reopen an index with aggressive merge plan options, and write a simple document. It triggers the merge and I poll StatsMap for the Tasks and TasksDone parameters. Once they converge, I close the index and reopen it read-only. Does that make sense?

**Comment by abourget** [comment]
Is it normal that the index grows exponentially (file size) with the number of documents indexed?

We're looking for a sweet spot between sharing indexes and index size.

**Comment by fproulx-eoscanada** [comment]
@sreekanth-cb hi again,

We've had great success with creating small indexes (of 2000 meta-documents, each containing varying number of documents with attributes). We parallel search over 2 terrabytes of indexes (15000 .bleve directories)

Now, that works well for now, but the reason we capped at 2000 was because going anywhere above 4000 or so we saw more and more and more diminishing returns, like the size of the index (after succesfully forcing the merge to flatten to about 6 files on average) we had an efficient ratio (documents to index size that was not linear.

Is this a bug in Bleve or inherent limitation due to the way the underlying index is organized ?

**Comment by mschoch** [comment]
Certainly there is nothing in the design of bleve/scorch that would cause us to expect the storage efficiency to go down as the index gets larger.  Every time the index grows enough to include more segments there is some inefficiency there because each segment has to duplicate some of the information.  But, generally as the segments get larger they should get more efficient.  To understand why, remember that as segments get large enough, eventually all the terms for a new document that you want to add are already in the term dictionary.  So larger segments should get more efficient at encoding documents.

Since with the data provided it appears the index is getting less efficient as it gets larger, it might be helpful to look closer at the individual files in the index and compute the efficiency for each.

The idea would be that for each file (segment) in the index, we know how many documents are in it, and how big it is on disk.  This might give us some clues, is it the larger files that show worse efficiency or is it the smaller ones?  Or maybe there is no pattern there, but worth exploring.

The other thing to consider is the usage pattern.  Deleted/Updated documents (as opposed to pure add) will also affect the numbers and make it appear that space is wasted.  Please clarify if there are any updates/deletes in your workload.

**Comment by fproulx-eoscanada** [comment]
We will investigate a bit deeper based on your insights.

@mschoch no, our documents are immutable, they are added once and never modified after first insertion.

**Comment by abourget** [comment]
Is there an indicator that merge has finished (until the next insertion).  We stop insertion to force a merge, but I'd like to have a deterministic indicator.. that allows me to close the index.

**Comment by mschoch** [comment]
@abourget there is an event fired when the merger makes progress, see: https://github.com/blevesearch/bleve/blob/master/index/scorch/event.go#L45

Also there are lots of stats related to merging as well, one could also poll these stats to find out the progress, see: https://github.com/blevesearch/bleve/blob/master/index/scorch/stats.go#L81-L108

**Comment by mschoch** [comment]
Also, I should add this level of detail about the internals of merging feels like a bit of an anti-pattern.  It might be preferable for us to add a synchronous ForceMerge() method, though that would require a lot more discussion...

**Comment by abourget** [comment]
Yeah, that's what I though. We're polling StatsMap() right now.. 

I don't know if it's useful to many to have a `ForceMerge()`.. it'd be better that way, that's for sure :)

**Comment by abourget** [comment]
did I say thanks for bleve? it's really cool :)

**Comment by fproulx-eoscanada** [comment]
@mschoch 👍 for officially sanctioned `ForceMerge`.... we've had to do it ourselves by polling stats (we poll `tasks == tasksDone` - we'll look into the events instead)

Right now I'm playing with the merge policy to find the right compromise for optimal efficiency (being careful about doing tasks on same exact set of documents to be more scientific)

**Comment by fproulx-eoscanada** [comment]
@mschoch @sreekanth-cb 
Hi again,

I've experimented with flipping various values of merge policy, always using the same exact documents for each attempts.

Now the "waste" from using bigger shards (10K meta-docs vs 5K vs 2K) is more reasonable (more like 50% extra disk space - ex. 2K = 1640 MB, 5K = 2100 MB, 10K = 2500 MB) - we can work with that.

Can you help me understand why the following values perform better than our initial random attempt.
```
"MaxSegmentsPerTier":   1,
"MaxSegmentSize":       50000,
"TierGrowth":           4.0,
"SegmentsPerMergeTask": 20,
"FloorSegmentSize":     2000,
"ReclaimDeletesWeight": 3.0,
```

**Comment by mschoch** [comment]
Oh I have no idea how those settings work.  My contention is that there should be no "waste" at all, I would expect "savings".

**Comment by fproulx-eoscanada** [comment]
@sreekanth-cb in order to make good comparison I've taken a subset of 10000 meta-documents (each containing about a hundred small Documents that are subject to the actual Bleve indexing).

We have one batch meta-document (so we batch index a batch of anywhere between a hundred to low thousands at a time). 

So I then take those documents and create 5 indexes of 2000 meta-documents or 2 indexes of 5000 meta-documents. In aggregate this encompasses the same exact documents, but they are spread out differently in terms of *.zap segments.

We prefer to have small indexes that we can pull on demand, that's why we determine a shard size in advance and only search those we care about (we have terrabytes of `.bleve` indices otherwise).

So those parameters perform relatively well - but I'd like to better understand how they interact with each other in terms of the Merge plan budget, etc. Some variations behave horribly so it's tricky...
```
"MaxSegmentsPerTier":   1,
"MaxSegmentSize":       50000,
"TierGrowth":           4.0,
"SegmentsPerMergeTask": 20,
"FloorSegmentSize":     2000,
"ReclaimDeletesWeight": 3.0,
```

**Comment by sreekanth-cb** [comment]
The merge planner works towards coming up with a plan to result in a logarithmic staircase of growing (bigger) segments. Something like this,
     
![image](https://user-images.githubusercontent.com/25240115/49694292-a7ec5f00-fbad-11e8-834d-a5a6d56cd8af.png)

And the merge policy arguments are for controlling different aspects as mentioned here: https://github.com/blevesearch/bleve/blob/eb8a688416aa5da15ea776cb6d6ba060c97ecfc4/index/scorch/mergeplan/merge_plan.go#L67

Please have a glance over there and let me know of further specific doubts, and I shall try to improve the documentation there to bring in more clarity.

**Comment by sreekanth-cb** [comment]
Closing this, as it seems there are no open items here.
Please re open this issue if there is any more concerns.
