### ISSUE TITLE
support int64, and possibly other numerical types

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#106]
currently we only support float64

**Comment by bcampbell** [comment]
This one tripped me up - I had a numeric field mapping set up on an `int` field, and was wondering why my queries weren't returning any results.

In fact, I'm kind of inclined to think that bleve should just panic if the data type is wrong, rather than just silently discarding the data...

(I had the same issue with a date/time field - I was trying to index a string struct memebr but I'm guessing bleve requires it as a time.Time)

**Comment by mschoch** [comment]
Yeah, this is an issue I hope to be returning to shortly.

I'm not sure I agree about the panic.  Bleve is designed to make the most out of your structures with minimal configuration.  But there will always be some things that it can't do anything with, without additional configuration.

What I could see is an option in the mapping to support a "strict mode".  In this mode we only index the fields that you explicitly map.  And, if there are any unexpected data types encountered, it should return an error.

Also, regarding your other issue, you can also map strings to be indexed as dates.  You just have to configure the appropriate datetime parser.  If you didn't provide an explicit mapping for the field, we first try to parse it with the default datetime_parser.  If that succeeds its indexed as a datetime.  If that fails we proceed to just index it as a string.  If you explicitly map the field as datetime, you can specify a different datetime_parser if the default one isn't correct for that field.

**Comment by bcampbell** [comment]
Ah, yes... I'd overlooked the working-without-configuration feature, which is a good goal.
In my case I was surprised because I'd explicitly specified a numeric field mapping on a couple of my int fields and was scratching my head when search results were never picking them up. I think I eventually stumbled across the float64 restriction in the mailing list.
Maybe an error should be set if an explicitly-defined fieldmapping encounters a datatype it doesn't handle? (although I realise it could be fiddly distinguishing between explicitly-set and default fieldmappings). I'll have a bit of a poke about in the code and see if I can come up with some more concrete thoughts.

Thanks for pointing out the custom datetime parsing (the `DateFormat` field in `FieldMapping`, I assume) - I'd missed that!

**Comment by mschoch** [comment]
Yep, great point.  I agree, if you explicitly map a particular field, but then the data can't be handled that probably should return an error.  I've opened a separate issue for this here: https://github.com/blevesearch/bleve/issues/224
