### ISSUE TITLE
Character Filter only works if the replacement string is a single whitespace char

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#1078]
Hi - I ran into a user who was trying to use the Character Filter as a string replacer, to replace a regexp with another string.  But, looks like there's some odd behavior.

In their case, they were working with address information, and wanted to replace a regexp of '\bst\b' (an "st" abbreviation bookended by word boundaries) with the string "street".  Oddly, the Character Filter surprisingly returned "streetstreet" (a doubled "street").

What's going on is the replacement string ("street") is repeated for the length of the original string len("st") == 2.  https://github.com/blevesearch/bleve/blob/master/analysis/char/regexp/regexp.go#L41

This works to expectation in the case when the replacement string is "" or " " (a single space char), as shown by the unit tests, like...

    input:  []byte(`<html>test</html>`),
    output: []byte(`      test       `),

The intention here seems to be to allow the replacement to be the same length of the original string, to allow for stable positioning or offsets of the text (so snippet & highlighting works?).  So, that behavior seems right when the replacement string is just a single space char.

But, if the replacement string is instead something else, the proposal or enhancement idea is to just use that replacement string as-is so that the Character Filter has more useful output.

**Comment by mschoch** [comment]
Yeah, basically if your character filter changes the length in any way, then highlighting will likely be wrong and/or panic.  So, to avoid that we made the decision that leads to the behavior reported here.

**Comment by mschoch** [comment]
I'm going to close this as a combination of fixed/invalid.  @abhinavdangeti has improved the behavior of the regexp char filter (https://github.com/blevesearch/bleve/issues/1372), so that it works more in-line with how users expect.  And we have fixed the highlighter to not crash.  However, using a char filter that makes replacements of different byte lengths, will still break highlighting.

If we have a proposal on how to improve/fix that, we should open a separate issue.
