### ISSUE TITLE
Write performance of boltdb for blevesearch is subpar at 1s delay at 10,000th item insertion using HDD

### ISSUE THREAD

**Issue by unisqu** [blevesearch/bleve#1086]
Write performance of boltdb for blevesearch is unacceptable.

I just realised this is true.
https://github.com/blevesearch/bleve/issues/1085

How do I use redis as connector? I will implement it then since boltdb is no longer actively maintained.

By the way, boltdb is truly really unacceptable. I don't understand why anyone can use it as a default backend for this. Redis please.

https://github.com/blevesearch/bleve/issues/1084

**Comment by mwmahlberg** [comment]
"Unacceptable" is a strong word, to say the least, especially when talking of a FOSS. Just because something does not fit *your* use case does not make something generally unacceptable. Personally, I would be devastated if support for (b)bolt would be dropped, and I strongly doubt I'd be the only one.

However, what is unacceptable is treating peers (or other human beings, for that matter) like servants.

@mschoch Sorry for the ranting, but this had to be said... ... I guess.

**Comment by mwmahlberg** [comment]
That being said, basically "all" you have to do is to implement the [KVStore interface](https://godoc.org/github.com/blevesearch/bleve/index/store#KVStore) (and [KVWriter](https://godoc.org/github.com/blevesearch/bleve/index/store#KVWriter) as well as [KVReader](https://godoc.org/github.com/blevesearch/bleve/index/store#KVReader), subsequently) to create a new KVStore which can be used with bleve.

**Comment by unisqu** [comment]
1. I can't find anywhere how to implement goleveldb properly or gtreap

https://gist.github.com/indraniel/1dc0243a27e600e3f297#file-toy-bleve-goleveldb-test-go
./toyleveldb.go:174:30: not enough arguments in call to bleve.NewUsing
        have (string, *mapping.IndexMappingImpl, string, map[string]interface {})
        want (string, mapping.IndexMapping, string, string, map[string]interface {})

2. if we have gtreap, I really can't understand why redis is not considered an option at all. Can someone pls help write a redis connector? Thanks.

**Comment by unisqu** [comment]
Will appreciate if there's a template for me to work on the redis connector. any templates?

**Comment by unisqu** [comment]
which files do i need only to modify? which do u suggest i work with first? gtreap or goleveldb store?

pls mention the files i need to modify and i'll get to work asap

**Comment by mwmahlberg** [comment]
@unisqu You are not getting the point. There is no "I simply change a line here and there and then it works". The interfaces I mentioned need to be implemented by **you**. From the ground up.

Let us take the basic KVStore interface. You would need to implement a type which has something like this

```
type KVRedis struct {
// your fields
...
}

func(kv *KVRedis)Writer() (KVWriter,error){
   writer:= RedisWriter{}
   ...
   return writer, nil
}
```

Of course, `RedisWriter` would need to implement `KVWriter`... and so on.

To make this even more clear: https://play.golang.org/p/mkI4Baw937p

**Comment by unisqu** [comment]
import (
        "github.com/gomodule/redigo/redis"
        "time"
)

var redisPool = RedisPool(3,120,240,"tcp","127.0.0.1:5679")

//c := redisPool.Get()
//defer c.Close()

func RedisPool(maxIdle, maxActive int, idleTimeout time.Duration, transProtocol, transData string) *redis.Pool {
        return &redis.Pool{
                MaxIdle: maxIdle,
                MaxActive: maxActive, // max number of connections
                IdleTimeout: idleTimeout * time.Second,

                Dial: func() (redis.Conn, error) {
                        c, err := redis.Dial(transProtocol, transData)
                        if err != nil {
                                panic(err.Error())
                        }
                        return c, err
                },
        }
}

type KVRedis struct {
    redisP *redisPool
}

... it's more complicated than i thought without proper documentation on how to write the connector.

can anyone give a clue? or can someone write this?

**Comment by mwmahlberg** [comment]
> it's more complicated than i thought without proper documentation on how to write the connector.

The interfaces are clearly defined. What more info is lacking?

**Comment by unisqu** [comment]
@mwmahlberg  can you give a clue on how to write the interface? I'll carry on the rest.

**Comment by unisqu** [comment]
@mwmahlberg I need to learn more about interface for golang first. i'm quite new to golang interface.

any possibilities anyone can get redis connector going? at least to SSDB connector

**Comment by sreekanth-cb** [comment]
@unisqu , just curious to know any specific reason for not using RediSearch?

**Comment by unisqu** [comment]
@sreekanth-cb i rather use manticore but i cant modify it easily. i can do golang. in fact i'm about to switch to manticore very soon if redis connector backend is not used for bleve.

my take on bleve compared with manticore (sphinxsearch), elasticsearch and redisearch (pure text)
1. bleve is the in between. speed wise is disappointing. it's at least 10x slower than the above mentioned alternatives in terms of indexing.

2. defeats the purpose of being implemented in golang without using redis / SSDB as backend.

**Comment by sreekanth-cb** [comment]
@unisqu , Have you tried the default moss store as the backend store or the newer "scorch" type index for your use case?

**Comment by mwmahlberg** [comment]
@unisqu Seriously? Ok, you asked for it.

- It is a server. With a rather messy authentication and authorization scheme. Let alone RBAC.
- It does not seem to have proper transaction support, unless you jump through a few hoops.
- Bleve is *not* Go's ElasticSearch. It is something you would build Go's ElasticSearch on. So you can rather compare it to Lucene - which stores it's data in a local K/V store *caughcaugh*. So in which way does it make sense to add network latency, additional dependencies, problematic security and additional administrative complexity?

> it's most logical that anyone will only consider redis.

No. Not at all. Personally, I am a fan of microservices. I use a rest frontend for bleve, which indexes various documents in a boltdb. So instead of accessing a common datastore with various bleve "clients", I access a single datastore via a REST API (with HA being provided by either Docker Swarm or Kubernetes). And since you need a persistent datastore anyway, be it for either boltdb or Redis, you have one less moving part when using the boltdb approach: the network connection between your bleve application and Redis.

That being said, I have forked bleve and created a boilerplate for you so that you can implement Redis. See the the [Redis store in the according feature branch](https://github.com/mwmahlberg/bleve/tree/feature/kvredis/index/store/redis). I have put in quite a few `// TODO` comments to let you know what your task at hand would be. This should be enough, and I am not going to do more, since I think it is of rather... ...questionable benefit -- as stated above.

hth

**Comment by unisqu** [comment]
> @unisqu Seriously? Ok, you asked for it.
> 
> * It is a server. With a rather messy authentication and authorization scheme. Let alone RBAC.
> * It does not seem to have proper transaction support, unless you jump through a few hoops.
> * Bleve is _not_ Go's ElasticSearch. It is something you would build Go's ElasticSearch on. So you can rather compare it to Lucene - which stores it's data in a local K/V store _caughcaugh_. So in which way does it make sense to add network latency, additional dependencies, problematic security and additional administrative complexity?
> 
> > it's most logical that anyone will only consider redis.
> 
> No. Not at all. Personally, I am a fan of microservices. I use a rest frontend for bleve, which indexes various documents in a boltdb. So instead of accessing a common datastore with various bleve "clients", I access a single datastore via a REST API (with HA being provided by either Docker Swarm or Kubernetes). And since you need a persistent datastore anyway, be it for either boltdb or Redis, you have one less moving part when using the boltdb approach: the network connection between your bleve application and Redis.
> 
> That being said, I have forked bleve and created a boilerplate for you so that you can implement Redis. See the the [Redis store in the according feature branch](https://github.com/mwmahlberg/bleve/tree/feature/kvredis/index/store/redis). I have put in quite a few `// TODO` comments to let you know what your task at hand would be. This should be enough, and I am not going to do more, since I think it is of rather... ...questionable benefit -- as stated above.
> 
> hth

thanks for the redis store. 
1. how do i use it? where do i declare the storage type in bleve? because most of the examples i can find online are not working. e.g.
https://gist.github.com/indraniel/1dc0243a27e600e3f297#file-toy-bleve-goleveldb-test-go

2. it seems great work! I will definitely try to implement it. I'm not sure where to influence the redis.Conn
connect() <- e.g. this connection, how do I call this part with the configuration details? e.g.

         var redisPool = RedisPool(3,120,240,"tcp","127.0.0.1:5679")

to 

         connect(3,120,240,"tcp","127.0.0.1:5679")

?

3. regarding redis, we will see after i implement and benchmark it. i only need solve question 2 and i think i'm ok with the rest. of course i really truly wish there's a working example even for goleveldb / gtreap so at least i have something to check.

**Comment by unisqu** [comment]
is it here?

for 1. with reference to 
https://gist.github.com/indraniel/1dc0243a27e600e3f297#file-toy-bleve-goleveldb-test-go


func makeBleveIndex(indexName string) bleve.Index {
	mapping := bleve.NewIndexMapping()

	//	index, err := bleve.New(indexName, mapping) // BoltDB default

//	kvstore := "goleveldb"
// to
	kvstore := "redis"

	kvconfig := map[string]interface{}{
		"create_if_missing": true,
		//		"write_buffer_size":         536870912,
		//		"lru_cache_capacity":        536870912,
		//		"bloom_filter_bits_per_key": 10,
	}

	index, err := bleve.NewUsing(indexName, mapping, kvstore, kvconfig)

	if err != nil {
		log.Fatalln("Trouble making index!")
	}
	return index
}

**Comment by mwmahlberg** [comment]
@unisqu Nailed it. See https://github.com/mwmahlberg/bleve/blob/feature/kvredis/index/store/redis/store.go#L25 for the configuration options to be set.

But again: **It is not implemented yet.** There is NO way of using it as is. You have quite  some implementation work to do *before* it is usable. Actually, in its current form it most likely won't even compile. Though the compiler errors should tell you what you need to do in order to get it running.

And even if I wanted to help: I could not, since I have yet to find a use case where Redis helps me.

**Comment by unisqu** [comment]
@mwmahlberg this is my first try at the reader
https://github.com/unisqu/bleve/blob/feature/kvredis/index/store/redis/reader.go

after reading your writer.go, i begin to understand what u mean with the transaction etc. 
basically i wont care about rolling back because prior to bleve insertion, the transactions will be in a message queue. and the "validity" of the queue will be determined pre data-entry/pre-processed.

that means whatever goes in to bleve will thus already been verified. (i dont see bleve as an acid db since it's just a search engine)

the message queue will be on the same localhost as bleve. if bleve goes down, i guess acidity won't matter in this case. I can accept search results not having immediate consistency.

After mentioning so, I also realised the application of bleve in your use case but if it's redis-enabled, manticore, lucene, elasticsearch will have a strong competitor. (please don't implement the MULTI-EXEC transaction on the redis module because I would like to use SSDB actually. MULTI-EXEC is ignored there too)

my rationale against boltdb is this benchmark here
https://github.com/siddontang/ledisdb/wiki/Benchmark

clearly, SSDB can be a better choice considering the use case i've stated.

**Comment by unisqu** [comment]
My use case for bleve is around 500 mil records of indexation data for blevesearch on HDD.
around 512bytes per record. I can optimize everything else.

Currently, indexation time needs to improve a lot. Because it's 1s per record insertion after 1k items.

**Comment by steveyen** [comment]
Hi @unisqu -- one other question -- wondering if you're using the batch API's of bleve during your indexing, versus indexing one doc at a time?  -- cheers, steve

**Comment by mwmahlberg** [comment]
@unisqu Well, how to put it... Reader has a [field `store`](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/reader.go#L11), which has a [field `conn `](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/store.go#L21) which actually is initialized in [New](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/store.go#L47). Yet, you keep using `redis.Dial`  to a static IP in `reader.go` instead of `r.store.conn`. That surely is not the way to go.

Please do not get me wrong, but implementing this is seems to be beyond your current skill level and cooperatively teaching you is well beyond the scope of a feature request.

So lets get back to the question brought up by @steveyen implicitly: Are you sure you used bleve with boltdb properly? Furthermore, a bit of math: 1s/10,000 = 100μs - not bad if you ask me.

**Comment by unisqu** [comment]
> @unisqu Well, how to put it... Reader has a [field `store`](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/reader.go#L11), which has a [field `conn `](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/store.go#L21) which actually is initialized in [New](https://github.com/unisqu/bleve/blob/42a5bb7141f9c97dc2e7ecfaeb89ce4f2be701a7/index/store/redis/store.go#L47). Yet, you keep using `redis.Dial` to a static IP in `reader.go` instead of `r.store.conn`. That surely is not the way to go.
> 
> Please do not get me wrong, but implementing this is seems to be beyond your current skill level and cooperatively teaching you is well beyond the scope of a feature request.
> 
> So lets get back to the question brought up by @steveyen implicitly: Are you sure you used bleve with boltdb properly? Furthermore, a bit of math: 1s/10,000 = 100μs - not bad if you ask me.
> 
> > We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. Yet we should not pass up our opportunities in that critical 3%"
> > _Donald Knuth_
@mwmahlberg 
1. yes you are right. i dont think i understand how to write this connector.
2. now it's 1s / 1 item addition at the 10,000th item. first item is already using 200ms to add.

@steveyen i'm adding one doc at a time.

**Comment by unisqu** [comment]
Given what you mentioned,

//	c, _ := redis.Dial("tcp","127.0.0.1:5679")
//        defer c.Close()
        

	b, err := redis.String(r.store.conn.Do("GET",string(key)))
	if err != nil  {
		return nil, nil
	}
	return []byte(b), err



is this correct? the problem is I missed the part where redis connection value is happening.

where do i put the 127.0.0.1:5679?

**Comment by mwmahlberg** [comment]
@unisqu Please, at least comment on the repo, and not here.

**Comment by unisqu** [comment]
@mwmahlberg can u provide issue requests on the repo to comment?

**Comment by unisqu** [comment]
can someone write the redis connector please?

**Comment by steveyen** [comment]
> @steveyen i'm adding one doc at a time.

Hi @unisqu -- I believe you should be able to see higher throughput by using bleve's Batch API and using large batch sizes.

**Comment by unisqu** [comment]
@steveyen can write the redis connector? so long as I can connect to the redis, i think i can write the rest.

**Comment by mwmahlberg** [comment]
I think this ought to be closed. It is not taking the project anywhere, nor is it foreseeable that it will lead to an improvement, let alone a PR.
