### ISSUE TITLE
bleve imports testing

### ISSUE THREAD

**Issue by Isolus** [blevesearch/bleve#1095]
I can't figure out where, but bleve somehow imports testing somewhere.

This is annyoing since it adds flags like in this example output:
```
./flagtest -h
Usage of ./flagtest:
  -test.bench regexp
    	run only benchmarks matching regexp
...
```

A minimal example shows that this is due to the inclusion of bleve or an imported package:
```
package main

import (
	"flag"
	_ "github.com/blevesearch/bleve"
)

func main() {
	flag.Parse()
}
```

**Comment by Isolus** [comment]
Probably caused by this closed bug. But the unfixed version from 2014(!) is still used: https://github.com/blevesearch/go-porterstemmer/issues/1

**Comment by evildecay** [comment]
It is really annoying, how can it not be displayed?

**Comment by mschoch** [comment]
What do you mean when you say "bleve is still using the unfixed version".

Bleve recommened versions of libraries are in the vendor/manifest file.  This points to the most recent commit of go-porterstemmer, where this issue seems to have already been fixed.

Go has never supported `dep` or Go modules.  We plan to support Go modules in the future.  If there is some thing we can do to make it play nicer with these, please let us know.

**Comment by Isolus** [comment]
I mean that in my case bleve is importing v1.0.1 of blevesearch/go-porterstemmer. Using bleve from a project using Go modules automatically imports the latest tagged version. And the latest tagged version of blevesearch/go-porterstemmer is outdated and doesn't include the fix.
So either bleve needs to support Go modules and use them to declare the correct version (like in the manifest) or better go-porterstemmer needs to tag the fixed version with a higher version number (e. g. v1.0.2).

**Comment by mschoch** [comment]
I just tagged the lastest go-porterstemmer as v1.0.2

https://github.com/blevesearch/go-porterstemmer/releases/tag/v1.0.2

**Comment by Isolus** [comment]
Works for me. Thanks!
