### ISSUE TITLE
gtreap store bug 

### ISSUE THREAD

**Issue by evildecay** [blevesearch/bleve#1132]
init gtreap store bug:
https://github.com/blevesearch/bleve/blob/master/index/store/gtreap/store.go#54
```go
//if path != "" {
//	return nil, os.ErrInvalid
//}
// Correct should be like this:
if path == "" {
	return nil, os.ErrInvalid
}
```

**Comment by mschoch** [comment]
I think the code is correct as is.  We are trying to ensure that the user did NOT specify a path.  If they did specify any non-empty path, it is invalid, since gtreap is an in-memory only solution.

**Comment by evildecay** [comment]
https://github.com/blevesearch/bleve/blob/master/index/store/gtreap/store.go#50
```go
        path, ok := config["path"].(string)
	if !ok {
		return nil, fmt.Errorf("must specify path")
	}
	if path != "" {
		return nil, os.ErrInvalid
	}
```
This is the code snippet that judges the path. Is there any contradiction here? Why do you have to specify the path above?

**Comment by mschoch** [comment]
I don't think there is a contradiction, just a sort of weirdness to the implementation.

The config map MUST contain key "path" with a value of type string AND that string MUST be the empty sting.  Otherwise, you will get one of the errors you see here.

Checking that the path is empty is an important last line of defense to ensure we don't accidentally create an in-memory only index when the user intended to persist it to disk.  And, due to the way we call this method, we know the key "path" will always be there.  Could this be done differently either here or elsewhere?  Maybe, but what problem are we trying to solve?

**Comment by evildecay** [comment]
OK. I understand what you mean. You are right, the memory index can only be created once, not repeatedly.
Thanks! @mschoch
```go
mapping := bleve.NewIndexMapping()
	index, err := bleve.NewUsing("", mapping, bleve.Config.DefaultIndexType, "gtreap", map[string]interface{}{})
	if err != nil {
		panic(err)
	}
	defer index.Close()
	for i := 0; i < 1000; i ++ {
		id := "ID_" + strconv.FormatInt(int64(i+1), 10)
		//fmt.Printf("DocID: %s\n", id)
		message := map[string]string{
			"id":   id,
			"from": "marty.schoch@gmail.com",
			"body": "bleve indexing is easy",
		}
		if err = index.Index(message["id"], message); err != nil {
			panic(err)
		}
	}
	q := bleve.NewPrefixQuery("id_9")
	req := bleve.NewSearchRequest(q)
	result, err := index.Search(req)
	if err != nil {
		panic(err)
	}
	for _, hit := range result.Hits {
		docid, err := index.Document(hit.ID)
		if err != nil {
			panic(err)
		}
		fmt.Println(hit.ID, docid.Fields[0].Name(), string(docid.Fields[0].Value()))
	}
```
