### ISSUE TITLE
Can bleve work with shared storage?

### ISSUE THREAD

**Issue by mbertschler** [blevesearch/bleve#1137]
Hello bleve team!

I tried out bleve for a project that I am working on where high availability is a requirement. So I started to implement a storage backend that uses a SQL database to see if this could be working.

The setup would look like this: many servers that use bleve as a library, but they all use the same shared storage.

Does bleve work correctly in that usecase, or would the library itself need some coordination between the servers above the storage layer?

Thank you for this awesome library!

**Comment by mschoch** [comment]
The short answer is that I don't think this is a good approach to pursue.

The longer answer is that yes it is possible, but I don't think you'll be happy with the solution.

Part 1 - How is it possible?

Bleve's default indexing scheme today is called `upsidedown`.  This index scheme can use any key/value store, provided it meets a few requirements.  All supported implementations are based on local file storage.  However, if you search the issues you'll find that someone has proposed we try every NoSQL product out there as a storage solution. They all really want the same thing, to have the distributed storage handle all the messy distributed system details for them.

Bleve's requirements for a key/value store also require 2 things.  First, you must be able to perform a batch of operations atomically.  That's OK, most NoSQL solutions can do this.  But, second, bleve must be able to perform multiple read operations from the same stable snapshot.  This is where most NoSQL solutions have limitations and are not a good fit.

However, you specifically said a SQL database, so it seems reasonable that you'll be able to use the features available to also have a stable read snapshot.

Part 2 - Why do I think this isn't a good idea?

First, I said that the current index scheme is called `upsidedown`.  But, the truth is we've been working on a new index scheme called `scorch`.  Scorch does not use pluggable key/value storage, so in this new index scheme it is no longer possible to plug in alternatives.

Why did we move to scorch?  The truth is that upsidedown has serious limitations that cannot be mitigated.  Even if we were to plug in some infinitely fast key/value storage, the architecture of how we encode the index into keys and values is problematic.

If people aren't happy with upsidedown when using a local key/value store, I'm fairly confident you will have an even worse experience with a distributed one.  The allure of letting the storage tier handle the messy distributed systems details comes with a price.  The distributed storage layer doesn't know what you're trying to do (it only see it as I/O) and this leads to further inefficiencies.

Part 3 - Opinions

My experience building highly available search solutions with bleve has been that it is better to use bleve as a library component only concerned with local storage/search of an index.  This allows you to choose a highly performant index scheme like `scorch`.  Then, you add your own distribution layer on top of this.  

One example of how this is advantageous over a shared storage solution:

Often with a search use case, when attempting to deliver high availability, it is OK to return partial results.  The thinking is that search results are inexact anyway, and you'd prefer to show users partial results instead of an error message.  When you have control over the networking/distribution part of the solution, you can engineer this capability.  With a shared storage solution, you may be stuck with undesirable behavior from shared storage (reads blocking) or if you can work around that, that logic is now inside of bleve where it may not belong.

**Comment by mbertschler** [comment]
Thank you for the very detailed answer @mschoch!
 
Yes indeed, using a shared storage seemed like a quick and dirty solution. The nice thing was that it wasn't hard to implement the SQL backend that worked in basic tests, but I had the feeling that it wasn't ideal, thats why I asked this question. I compared it against the `boltdb` backend, and the performance hit was very visible (at least a 10x slower). I have seen the new `scorch` index mentioned yet, haven't used it yet but I will check it out! 

Implementing the distribution above the library is of course more effort, but I understand why this would be better for the overall system. Thank you for the insights!
