### ISSUE TITLE
Problem getting match, what can be wrong

### ISSUE THREAD

**Issue by lundin** [blevesearch/bleve#114]
Hi!
Great go library. However i can not make it work the way i expect it to work. I am on MAC, i have build libstemmer and the .h is in the include folder.

I have build with tags libstemmer and i get no errors upon compling my indexer go code
I have created a index with a custom mapper:

```
indexMapping := bleve.NewIndexMapping()
    var err error

    err = indexMapping.AddCustomTokenFilter("ngramy",
        map[string]interface{}{
            "type": "ngram",
            "min":  5.0,
            "max":  25.0,
        })
    if err != nil {
        fmt.Println(err)
    }

    err = indexMapping.AddCustomAnalyzer("swspec",
        map[string]interface{}{
            "type":         "custom",
            "char_filters": []interface{}{},
            "tokenizer":    "unicode",
            "token_filters": []interface{}{
                "stemmer_sv",
                "stop_sv",
                "ngramy",
            },
        })
    if err != nil {
        fmt.Println(err)
    }

    index, _ := bleve.New("parts98.bleve", indexMapping)
```

Then i batch some parts and query for a match

```
var messagepack []Unicorn

    batch := bleve.NewBatch()
    for i := 0; i < 1; i++ {
        la := i*1000 + 1
        ds := strconv.Itoa(la)
        fmt.Println(ds)
        message := Unicorn{
            Id:   i,
            Sku:  ds,
            From: "me",
            Body: "baklucka helt utan repor och i bra skick. Passar till de flesta 900 serier. Måste ses!",
        }

        messagepack = append(messagepack, message)
        batch.Index(string(i), message)

    }

    index.Batch(batch)

    query := bleve.NewMatchQuery("passar")
    searchRequest := bleve.NewSearchRequest(query)
    searchRequest.Highlight = bleve.NewHighlight()

    searchResult, _ := index.Search(searchRequest)

    fmt.Println(searchResult.String())
    fmt.Println(searchResult.Hits)

    for _, hit := range searchResult.Hits {
        res1B, _ := json.Marshal(hit)
        fmt.Println(string(res1B))

    }

```

This is "swedish" btw. I can get hits and highlight on passar (which is a word that is contained within the body string). However backlucka does not match, nor any stemmer or backl or anything that should be the case from the ngram.

I really dont understand what i am doing wrong here.

The explorer (online version), seems to index it just fine. 

Any ideas ? Oh and sorry for the messy code, i am new to go as well =)

Thanks!

**Comment by kamna123** [comment]
Hi, I am new to blevesearch. I have one query. 
Can we check for nil or exact match for some field in blevesearch.

**Comment by kamna123** [comment]
I need to find fields where exact match is there or that field is not set(nil value). Can you please help me out.

**Comment by mschoch** [comment]
@kamna123 since you are new to blevesearch so should know that it is inappropriate to ask the same question on three different existing bugs.  Finding an exact match between a term you're looking for and a term in the index is done with a TermQuery.  However, if you want the index to contain the "exact" contents of a field, you have to index it with that in mind (normally we transform text during indexing).  To index the exact, unaltered original text of a field, you must index it using the 'keyword' analyzer.  Currently, we have no way to find nil values.  They do not produce anything in the index, and thus cannot be searched for.  The only way to work around that today would be to alter them to index some other value that could be searched for.  In the future, you should ask your questions in a new issue, and only do so once.
