### ISSUE TITLE
Indexing time increases X7 after 9000 documents 

### ISSUE THREAD

**Issue by hubyhuby** [blevesearch/bleve#1232]
After indexing about 9 000 documents, the  "average ms/doc" increases by X7.
Maybe it is a normal beahviour as some background works kicks in on the index.
Also It seems that the average increases and then stays there at a higher level(only 30K documents tested).
I would expect two scenarios : 1) The increase would be linear. 2) there is a sort of "background garbage" running that would spike for few milliseconds. And then the average would come back to 0.14ms/doc (on my machine).

If it is a normal beahviour please close the bug ( I thought it was worth notifying, even if it is just an optimisation issue).

I did the test 3 times on beer search example  :
* RUN 1: 
2019/04/19 14:37:39 Indexed 1000 documents, in 0.14s (average 0.14ms/doc)
2019/04/19 14:37:39 Indexed 2000 documents, in 0.28s (average 0.14ms/doc)
2019/04/19 14:37:39 Indexed 3000 documents, in 0.42s (average 0.14ms/doc)
2019/04/19 14:37:39 Indexed 4000 documents, in 0.56s (average 0.14ms/doc)
2019/04/19 14:37:40 Indexed 5000 documents, in 0.70s (average 0.14ms/doc)
2019/04/19 14:37:40 Indexed 6000 documents, in 0.83s (average 0.14ms/doc)
2019/04/19 14:37:40 Indexed 7000 documents, in 0.98s (average 0.14ms/doc)
2019/04/19 14:37:42 Indexed 7303 documents, in 2.93s (average 0.40ms/doc)

* RUN 2 :
2019/04/19 14:38:57 Indexing...
2019/04/19 14:38:57 Indexed 1000 documents, in 0.04s (average 0.04ms/doc)
2019/04/19 14:38:57 Indexed 2000 documents, in 0.09s (average 0.04ms/doc)
2019/04/19 14:38:57 Indexed 3000 documents, in 0.12s (average 0.04ms/doc)
2019/04/19 14:38:58 Indexed 4000 documents, in 0.16s (average 0.04ms/doc)
2019/04/19 14:38:58 Indexed 5000 documents, in 0.20s (average 0.04ms/doc)
2019/04/19 14:38:58 Indexed 6000 documents, in 0.24s (average 0.04ms/doc)
2019/04/19 14:38:58 Indexed 7000 documents, in 0.28s (average 0.04ms/doc)
2019/04/19 14:39:00 Indexed 7303 documents, in 2.40s (average 0.33ms/doc)

* RUN 3 : with 10MB of data = 4X 2,5mb beer search files
2019/04/19 14:42:54 Indexing...
2019/04/19 14:42:54 Indexed 1000 documents, in 0.04s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 2000 documents, in 0.08s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 3000 documents, in 0.11s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 4000 documents, in 0.16s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 5000 documents, in 0.19s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 6000 documents, in 0.22s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 7000 documents, in 0.27s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 8000 documents, in 0.31s (average 0.04ms/doc)
2019/04/19 14:42:54 Indexed 9000 documents, in 0.38s (average 0.04ms/doc)
2019/04/19 14:42:57 Indexed 10000 documents, in 2.77s (average 0.28ms/doc)
2019/04/19 14:42:57 Indexed 11000 documents, in 2.80s (average 0.25ms/doc)
2019/04/19 14:42:57 Indexed 12000 documents, in 2.83s (average 0.24ms/doc)
2019/04/19 14:42:57 Indexed 13000 documents, in 2.86s (average 0.22ms/doc)
2019/04/19 14:42:57 Indexed 14000 documents, in 2.90s (average 0.21ms/doc)
2019/04/19 14:42:57 Indexed 15000 documents, in 2.93s (average 0.20ms/doc)
2019/04/19 14:42:57 Indexed 16000 documents, in 2.96s (average 0.19ms/doc)
2019/04/19 14:42:57 Indexed 17000 documents, in 2.99s (average 0.18ms/doc)
2019/04/19 14:42:57 Indexed 18000 documents, in 3.03s (average 0.17ms/doc)
2019/04/19 14:42:57 Indexed 19000 documents, in 3.06s (average 0.16ms/doc)
2019/04/19 14:42:59 Indexed 20000 documents, in 5.04s (average 0.25ms/doc)
2019/04/19 14:42:59 Indexed 21000 documents, in 5.07s (average 0.24ms/doc)
2019/04/19 14:42:59 Indexed 22000 documents, in 5.10s (average 0.23ms/doc)
2019/04/19 14:42:59 Indexed 23000 documents, in 5.13s (average 0.22ms/doc)
2019/04/19 14:42:59 Indexed 24000 documents, in 5.16s (average 0.22ms/doc)
2019/04/19 14:42:59 Indexed 25000 documents, in 5.19s (average 0.21ms/doc)
2019/04/19 14:42:59 Indexed 26000 documents, in 5.23s (average 0.20ms/doc)
2019/04/19 14:42:59 Indexed 27000 documents, in 5.26s (average 0.19ms/doc)
2019/04/19 14:42:59 Indexed 28000 documents, in 5.29s (average 0.19ms/doc)
2019/04/19 14:42:59 Indexed 29000 documents, in 5.32s (average 0.18ms/doc)
2019/04/19 14:43:01 Indexed 29212 documents, in 7.42s (average 0.25ms/doc)

**Comment by mschoch** [comment]
Can you clarify which index scheme and if it's upsdiedown also which kvstore you're using?

Also, can you elaborate on what/how you changed for run 3, such that you have more than 7303 docs?

And what does 'with 10MB of data = 4X 2,5mb beer search files' mean?

**Comment by hubyhuby** [comment]
I have been using the little example I put together here : https://github.com/hubyhuby/bleve-search-example
I am using the scorch index : beerIndex, err = bleve.NewUsing(*indexPath, indexMapping, "scorch", "scorch", nil)
I have basically copied & past the "beer search" example JSONs 4 times in the same data folder. 

Hope this help. If the behavior seems normal to you. That s fine to close it; as far as I am concerned I don't need more performance in this area.

**Comment by mschoch** [comment]
The most likely explanation for the performance changing so drastically is the following:

1) new batches come into the system, and each becomes it's own segment
2) initially there is nothing else to do, so perf is consistent
3) eventually there are now enough segments of similar size that it becomes a problem, and the merger needs to take several segments and combine them into a larger one.  at this point, latency involved in indexing a batch would go up, because the merger is also using up some I/O bandwidth.
4) merging is considerably slower than simply persisting new segments, so there is another situation you can run into, where we have a very large number of segments that the merger hasn't even considered.  when you reach this point, we eventually pause persisting segments to let the merger catch up.

The reason that the observed performance doesn't degrade smoothly is that the unit of granularity here is a segment.  Larger batches mean larger segments, and this is good for improving overall throughput of the system, but it also means latency suffers because large batches/segments have to be managed atomically.

There are settings that can be tweaked, but these types of changes aren't magic "make everything faster", they adjust trade-offs making one thing faster and other things slower.  So, unless you have a particular problem you're trying to solve, you're better off leaving it as is.

**Comment by hubyhuby** [comment]
Thanks a lot @mschoch for reviewing this issue and for developing this wonderful search library.

This explain the reasons for this normal increase. This is not an issue , just a regular behavior of indexing.
Closing.
