### ISSUE TITLE
partial search - fuzzines wont return result

### ISSUE THREAD

**Issue by serkandemirel0420** [blevesearch/bleve#1287]
I have come up below code  but not to sure how to move forward. 

In short i am trying get result for such case,

When searched "ome" i need "bbb something aaa" to be found. Have tried to add
`tq.SetFuzziness(5)` but this causes ap to crash without any error. I would appreciate any help.

```
                param := c.DefaultQuery("param", "")

		split := strings.Split(param, " ")

		tqs := make([]query.Query, len(split))
		for i, token := range split {
			tq := bleve.NewFuzzyQuery(token)
			tq.SetField("Content")
			tqs[i] = tq
		}

		allQuery := bleve.NewConjunctionQuery(tqs...)

		req := bleve.NewSearchRequest(allQuery)
		req.Highlight = bleve.NewHighlightWithStyle("html")
		req.Fields = []string{"ID", "Title", "Content", "RawContent"}
		res, err := index.Search(req)
```

**Comment by mschoch** [comment]
If the app crashes, you should file a bug for that, and if possible include code to reproduce the crash.

Fuzzy search with high enough fuzziness would eventually match in theory (but the implementation rejects using too high a fuzziness).  Even if it didn't you wouldn't be happy with the results because the fuzziness will cause it to match lots of other things completely unrelated to "ome".

Your next option is to us a wildcard or regex query to match the terms.  But that too would only work if you indexed a field containing "bbb something aaa" as a single term.  But, be aware that this only matches individual tokens in the index, not across multiple terms, and is the fully analyzed terms, not the originals.

**Comment by serkandemirel0420** [comment]
Thank you mschoch, i will file bug soon. Not sure though if i am doing something wrong, need to be more sure about it before filing.

In addition to that, i can ask another question.
How can i search on spesific field by using `NewQueryStringQuery()` but want to get all fields saved in the index?

Thanks a lot.
