### ISSUE TITLE
how to match the whole query phrase

### ISSUE THREAD

**Issue by orange-jacky** [blevesearch/bleve#1322]
mappings
`// a generic reusable mapping for english text
	englishTextFieldMapping := bleve.NewTextFieldMapping()
	englishTextFieldMapping.Analyzer = en.AnalyzerName
	englishTextFieldMapping.Store = true
	englishTextFieldMapping.IncludeInAll = true

	// a generic reusable mapping for keyword text
	//	keywordFieldMapping := bleve.NewTextFieldMapping()
	//	keywordFieldMapping.Analyzer = keyword.Name

	docMapping := bleve.NewDocumentMapping()

	docMapping.AddFieldMappingsAt("id", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("cnname", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("citycode", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("citycn", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("enname", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("country", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("country_code", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("province", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("cityen", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("city_pinyin", englishTextFieldMapping)
	docMapping.AddFieldMappingsAt("city_jianpin", englishTextFieldMapping)

	indexMapping := bleve.NewIndexMapping()
	indexMapping.DefaultAnalyzer = "en"
	indexMapping.DefaultMapping = docMapping
	//indexMapping.IndexDynamic = true
`
query
`func  Search(q string, from, size int) (items []interface{}, err error) {

	var searchQuery query.Query
	if q != "" {
		queryId := query.NewMatchPhraseQuery(q)
		queryId.SetField("id")
		queryCnname := query.NewMatchPhraseQuery(q)
		queryCnname.SetField("cnname")
		queryCitycode := query.NewMatchPhraseQuery(q)
		queryCitycode.SetField("citycode")
		queryCitycn := query.NewMatchPhraseQuery(q)
		queryCitycn.SetField("citycn")
		queryEnname := query.NewMatchPhraseQuery(q)
		queryEnname.SetField("enname")
		queryCountrycode := query.NewMatchPhraseQuery(q)
		queryCountrycode.SetField("country_code")
		queryCountry := query.NewMatchPhraseQuery(q)
		queryCountry.SetField("country")

		disQuery := bleve.NewDisjunctionQuery()
		disQuery.AddQuery(queryId, queryCnname, queryCitycode, queryCitycn, queryEnname, queryCountrycode, queryCountry)
		searchQuery = disQuery
	} else {
		searchQuery = bleve.NewMatchAllQuery()
	}

	searchRequest := bleve.NewSearchRequestOptions(searchQuery, size, from, true)
	searchRequest.Fields = []string{"id", "cnname", "citycode", "citycn", "enname", "country_code", "country"}
	searchRequest.SortBy([]string{"-id"})

	searchResult, err := b.index.Search(searchRequest)
	if err != nil {
		return
	}
	//fmt.Println(searchResult)
	for _, v := range searchResult.Hits {
		items = append(items, v.Fields)
		//	fmt.Printf("no%d %s %s %v\n", i, v.Index, v.ID, v.Fields)
	}
	return
}`

when i run  search("bjs", 0., 10), i want query match the whole bjs phrase documents,but i found that it return a document not match the whole phrase bjs.
the doc1 is 
{
    "_id" : "COO",
    "cnname" : "科托努机场",
    "citycode" : "COO",
    "citycn" : "科托努",
    "enname" : "Cadjehoun",
    "country" : "贝宁",
    "province" : "",
    "cityen" : "Cotonou",
    "country_code" : "BJ",
    "region_code" : "AF"
}

how to make search("bjs", 0., 10) not match the doc1 only match documents which has whole bjs string

**Comment by orange-jacky** [comment]
Is anyone still maintaining it?

**Comment by mschoch** [comment]
@orange-jacky yes.  I am doing the best I can, however it has been difficult to find financial support to continue working on bleve.

As for this issue, I do not understand your question.  Is "bjs" the actual query string you're passing to the search function?  Since "bjs" is a single token, and all of the values in the document appear to also be single tokens, then I don't understand why you're using PhraseQuery at all.

Can you provide an example (that bleve developers can run locally) that illustrates your problem?

**Comment by orange-jacky** [comment]
@mschoch  i will post an example to here

**Comment by orange-jacky** [comment]
@mschoch  i post the example 
[code.zip](https://github.com/blevesearch/bleve/files/4069229/code.zip)

for example, i have some docs
map[citycn:科托努 citycode:COO cnname:科托努机场 country:贝宁 country_code:BJ enname:Cadjehoun]
map[citycn:北京 citycode:BJS cnname:北京南苑机场 country:中国 country_code:CN enname:BEIJING]
map[citycn:北京 citycode:BJS cnname:北京首都国际机场 country:中国 country_code:CN enname:BEIJING]
map[citycn:北京 citycode:BJS cnname:北京大兴国际机场 country:中国 country_code:CN enname:BEIJING]

when i search("BJS")， i want to match the whole pharse "BJS",  it should return  three records
map[citycn:北京 citycode:BJS cnname:北京南苑机场 country:中国 country_code:CN enname:BEIJING]
map[citycn:北京 citycode:BJS cnname:北京首都国际机场 country:中国 country_code:CN enname:BEIJING]
map[citycn:北京 citycode:BJS cnname:北京大兴国际机场 country:中国 country_code:CN enname:BEIJING]

, not contain 
map[citycn:科托努 citycode:COO cnname:科托努机场 country:贝宁 country_code:BJ enname:Cadjehoun]

it search "BJS" phase it should not match BJ, it should match whole "BJS" phase

**Comment by mschoch** [comment]
Thank you for provide an example I could run and experiment with locally, it made this much easier for me to assist with.

1.  The reason that a search for "BJS" matches a document with the value "BJ" in the field is due to the text analyzer you have selected.  The "en" analyzer performs stemming on all terms before they are placed into the index.  So if we look inside the index, for the item with _id = COO, we would find that the country code is recorded as "bj".  Next, at search time, you're using a MatchPhraseQuery.  Query types that include the word "Match" also use the same analyzer for that field, so your search for "BJS" gets converted to a search for "bj".  As far as bleve is concerned, this is an exact match.

2.  If you want to better understand how the analyzers work I suggest you try this:

http://analysis.blevesearch.com/analysis

You can select "en" and enter the text "BJS" and see the output yourself.

3.  You are using MatchPhraseQuery, but all of the text values appear to be a single token.  In this case the Phrase portion of the query is not doing anything, and I would suggest simply using a MatchQuery instead.  However, that does not fix the underlying issue you have reported.

As I understand it, you only want exact matches, so you should choose an analyzer that does not perform any stemming.  You could try using "standard", however that will still lower-case the terms in the index for case-insensitive matching.  If you want to match exact case as well, you should use the "keyword" analyzer.

**Comment by orange-jacky** [comment]
@mschoch  how to support the fllowing example?
for example  
 search "bj"   match all matched "bj"，“BJ”, "bJ", "Bj" 的？
 search "北京"  match all matched "北京"

**Comment by orange-jacky** [comment]
thanks
