### ISSUE TITLE
Excluding all fields from indexing in documents by default?

### ISSUE THREAD

**Issue by ScaleToInfinity** [blevesearch/bleve#1354]
First of all, thanks for building such an awesome pkg! 

I've build an interface to quickly index any of my structs in Bleve, my goal is to only index specific fields explicitly stated.

I've played around with the examples in your documentation, and looked a bit into how default mappings works. I'm not really have a lot of success here, so I'm hoping you could point me in the right direction :-)

**Comment by mschoch** [comment]
I just saw this and it's already closed.  Were you able to figure out the problem you were having?

**Comment by ScaleToInfinity** [comment]
Love your engagement :fire: 

I actually closed this because I was trying another route and wanted to give it a try. It did not turn out the way I hoped I'm afraid. 

I'd still love your input on this!.. I'm trying to create a really fast indexing pkg that we will use internally for our ecommerce microservices all written in Go. I've went with storing the entire objects in a sync.map and my idea here is to use Bleve to quickly retrieve documents to fetch from the sync.map. 

Bonus info: I benchmarked both the upsidedown index and Scorch, but the upsidedown seems to perform best for what I'm using it for (only keyword analysers).

**Comment by mschoch** [comment]
First, it would be great if you can share you benchmark.  In our testing scorch is significantly faster for all use cases, and we have essentially abandoned upsidedown.  We hope to deprecate it soon, but currently still rely on it for in-memory only indexes.

If you are using the IndexMapping's DefaultMapping (meaning you're not configuring separate mappings for multiple types), then you would do this by using what we call a "static" mapping.  Here static just means the opposite of dynamic, and our dynamic mappings automatically try to index everything.  So somthing like:

```
// start by disabling the automatic indexing
docMapping := bleve.NewDocumentStaticMapping()

// add explicit field mappings for the fields you want to index here
docMapping.AddFieldMappingsAt("fieldA", ....)
docMapping.AddFieldMappingsAt("fieldB", ....)

// create the index mapping
mapping := bleve.NewIndexMapping()
// set the index mapping's default mapping to the default mapping you just build
mappinig.DefaultMapping = docMapping
```

**Comment by ScaleToInfinity** [comment]
Sure thing, I'd love to do that. First I think I need to fill you in on some project details. 

This is a memory only index we would like to respond within a total of 1-3 ms through gRPC endpoints with 280k items with all our website products in same index (or 8.6k ish in seperate).

Thanks for your example! That managed to get me up and running on the exclude part. 

With the memory only in part, would you still like to insight into the use case and benchmarks? 
Do you have any optimization ideas?

Currently I'm using an Index that looks like this:

`	defaultDocMapping := bleve.NewDocumentStaticMapping()
	defaultDocMapping.DefaultAnalyzer = keyword.Name

	for _, fieldMapping := range iOptions.fieldMappings {
		defaultDocMapping.AddFieldMappingsAt(fieldMapping.Name, fieldMapping)
	}

	mapping := bleve.NewIndexMapping()
	mapping.DefaultAnalyzer = keyword.Name
	mapping.DefaultMapping = defaultDocMapping

	index, err := bleve.NewMemOnly(mapping)`

So what I'm using Bleve for here is filtering and pagination of exact matches (keywords) in a memory index for performance.

**Comment by mschoch** [comment]
OK, so when you call `NewMemOnly()` bleve is hard-coded to use upsidedown with a particular KV store (gtreap).  There are ways to create in-memory only indexes with `NewUsing()`, but as of today it's impossible to do so with the scorch index type.  Scorch will always persist data to disk, so unless you have set up a RAM disk, it always goes to disk.

This is something we hope to fix, because there is no reason we can't have an in-memory scorch and we believe it would perform better. It's just not trivial because of some other design decisions inside of scorch.

But, there may still be some things to try which may help your use case.

Couchbase found that they needed a in-memory index for some use cases, and in their testing, they found that using an index with the `moss` key-value store was faster than the one Bleve uses by default.

They manually configure this by using the more advanced `bleve.NewUsing()` function:

https://github.com/couchbase/n1fty/blob/7915809b898cf81b879ac4a59880cc9f5eb7df22/verify/verify_result.go#L138-L139

And the config map they pass in is defined here:

https://github.com/couchbase/n1fty/blob/7915809b898cf81b879ac4a59880cc9f5eb7df22/verify/verify_result.go#L38-L42

I'm going to ping @sreekanth-cb and @abhinavdangeti to see if there is anything else important you should know.

There is one other thing that might help.  Since you are only looking for exact matches, the scoring functionality in bleve is useless to you.  Again, Couchbase also had need for that in a different use-case, and they added this field:

https://github.com/blevesearch/bleve/blob/master/search.go#L279

It can be used to disable scoring, however it doesn't seem we documented the correct values to pass in here (that I can find right now).  Again if @sreekanth-cb or @abhinavdangeti could help out that would be great.

I think if we try these two things, your performance goals seem reasonable, but I have no idea how attainable they are as it's not something we've tried.

**Comment by ScaleToInfinity** [comment]
Wow, really impressed by your efforts in helping everyone out using Bleve. Keep up the great work!

Here is some benchmarks and comments while implemented what you suggested above :+1: 

Before tuning: ---------------------------------------

```
Summary:
  Count:	1000
  Total:	9.10 s
  Slowest:	15.14 ms
  Fastest:	6.92 ms
  Average:	9.01 ms
  Requests/sec:	109.90

Latency distribution:
  10 % in 7.91 ms 
  25 % in 8.24 ms 
  50 % in 8.82 ms 
  75 % in 9.64 ms 
  90 % in 10.24 ms 
  95 % in 10.76 ms 
  99 % in 12.02 ms 
```

Edit 1: With Moss: -------------------------------------------

Using their config map the response time went up to 2 seconds, without looking more into that I tried booting Moss up with default config, and the gave the results bellow! 

```
Summary:
  Count:	1000
  Total:	4.58 s
  Slowest:	14.80 ms
  Fastest:	3.52 ms
  Average:	4.50 ms
  Requests/sec:	218.40

Latency distribution:
  10 % in 3.74 ms 
  25 % in 3.93 ms 
  50 % in 4.20 ms 
  75 % in 4.58 ms 
  90 % in 5.71 ms 
  95 % in 6.59 ms 
  99 % in 8.91 ms 
```

Edit 2: Disabling Scoring: ------------------------------------
Seems like they made a test for it that states the desired value here: https://github.com/blevesearch/bleve/blob/b7a0cb6a1d4fdbaeb7ab5bdec6a9732b995e39a0/search_test.go#L1578 

Using that gave a little bit more speed!

```
Summary:
  Count:	1000
  Total:	4.27 s
  Slowest:	14.99 ms
  Fastest:	3.54 ms
  Average:	4.19 ms
  Requests/sec:	234.40

Latency distribution:
  10 % in 3.67 ms 
  25 % in 3.85 ms 
  50 % in 4.07 ms 
  75 % in 4.39 ms 
  90 % in 4.72 ms 
  95 % in 4.96 ms 
  99 % in 6.13 ms 
```

_____________________________________________

That's amazing, thanks a ton! 

I'd be happy to tune it even further if anyone comes up with great ideas.. one that I've been having is create an index for each website, that would greatly reduce the amount of entries, and removing the need for a term filter on website. 

I tried testing this though, and the bleve.NewMatchAllQuery() increases the response times to 10-12 ms, so unless there is a better way to match documents in this smaller index this seems less efficient.

**Comment by mschoch** [comment]
Glad to hear this helped some.

If many of the queries are constrained to a single index, I would expect breaking the indexes up to help.  But I'm not clear why you then need a MatchAllQuery, as you would typically then just use a query with the remaining query clauses, after manually selecting the correct index.

And for queries that don't specify a specific website, you would search across multiple (or all) indexes by using the IndexAlias feature of bleve.  That might incur some additional cost, but you would have to weigh that cost based on your knowledge of the types of queries you need to support.

Or, if you're only concern is query time and you have additional resources at index time, you could index them both ways, individually and together, and get the best of both options.  It sounds like you have some aggressive performance numbers to hit, but you're close, so you might have to get creative.

**Comment by ScaleToInfinity** [comment]
Thanks for your work here, I think we pretty much reached our goals at this point. 

We're exited to see it hit production this monday, thanks for your help! 

I'll go ahead and close this. All the best!
