### ISSUE TITLE
French text mapping and search problem + asciifolding 

### ISSUE THREAD

**Issue by popsUlfr** [blevesearch/bleve#1362]
Hello,

I might have some trouble understanding the document mappings or there is something wrong with how it works.

Here are following cases which don't seem to produce the intended outcome : 

https://gist.github.com/popsUlfr/d9233df57643e567f219d3d469e1002f

The first example adds a TextFieldMapping for the `text_content` field with french default analyzer. But when searching for `chômeur` it doesn't match anything, unless the french analyzer is not used as default for the text field.

Changing the first part like this (document mapping instead of static document mapping) : 

```
wrmap := bleve.NewDocumentMapping()
wrmap.DefaultAnalyzer = fr.AnalyzerName
//txtmap := bleve.NewTextFieldMapping()
//txtmap.Analyzer = fr.AnalyzerName // commenting this line makes it work ?
//wrmap.AddFieldMappingsAt("text_content", txtmap)
```

manages to find the term, so it might be the case that I didn't fully understand how field mappings work.

The second example I made a custom analyzer `frplus` which adds the asciifolding character filter. I'd like to search for `chomeur` and find the term but that doesn't work.

Any pointers would be appreciated.

**Comment by mschoch** [comment]
In the first example, the problem is that you set up a custom analyzer for the `text_content` field, but then the search you run did not specify a field.  Your search operated on the `_all` field, but when searching the `_all` field, the default analyzer for the index is used, so no match is found.  That is why when you removed the french analyzer line, you got a match, because then the default analyzer was used.  That is the key principle for search to work, the same analyzer has to be used at index and query time.

Another way to illustrate it is this, if I change your query to `"text_content:chômeur"` this scopes the search to the `text_content` field, and then it also knows to use the french analyzer.

A third solution would be make french the default analyzer (this is the best solution if all of your fields will use the same language).

Your second example is close, and just has the same problem.  Here is an example of the other option I described, making your custom analyzer the default:

```
	//wrmap := bleve.NewDocumentStaticMapping()
	//txtmap := bleve.NewTextFieldMapping()
	//txtmap.Analyzer = "frplus"
	//wrmap.AddFieldMappingsAt("text_content", txtmap)

	im := bleve.NewIndexMapping()
	//im.AddDocumentMapping(WebResource{}.Type(), wrmap)
	im.DefaultAnalyzer = "frplus"
```

With this change the second example now works as well.

**Comment by popsUlfr** [comment]
@mschoch Ooh thank you for the clarifications! So, the search on `_all` only uses the analyzer set as the DefaultAnalyzer of the index mapping ? Default analyzers in subdocuments of the index mapping are therefore not taken into account while searching ? That's where I had the wrong idea it seems. The field mappings tell how to handle individual fields (dates, numbers, booleans, etc...)

Do you happen to know why the highlight is broken ?

```
1 matches, showing 1 through 1, took 90.321µs
    1. 1 (0.040644)
        text_content
                …iles au plus grand nombre tous ?_

        ## [](#le-contexte) Le contexte

        “TZCLD: Territ<mark>oire z�</mark>�ro chômeur de longue durée” est une expérimentation sur territoire français menée afin de trouver une nouvel…
```

Is it because the asciifolding filter has generated indexed text which term positions do not match the stored field value anymore ? Is there a way to fix that ?

**Comment by mschoch** [comment]
So the `_all` field will get the contents of the other fields using the field-specific analyzer at index time.  The problem is that at query time, unless the user specifies a field, we search the `_all` field with the default analyzer, which is not going to work for fields with custom analyzers.

If you need to support many different fields with many different analyzers, you probably have to do some query rewriting internally to ensure the right analyzers are used when searching fields (not something you would expect end users to do).

Regarding the highlighting, yes I think that is known issue in bleve today.  If the char_filter alters the byte offsets from the original input, highlight may be wrong or possible even crash.  I was just talking with @abhinavdangeti about this last week.  @abhinavdangeti can you see if the proposed ideas we talked about would work for this case too?  Perhaps we should open a separate ticket to track it.

**Comment by popsUlfr** [comment]
I added another test where asciifolding is used as TokenFilter and highlighting seems ok now : https://gist.github.com/popsUlfr/d9233df57643e567f219d3d469e1002f#file-frtestbleve3-go

```
1 matches, showing 1 through 1, took 99.688µs
    1. 1 (0.041757)
        text_content
                …au plus grand nombre tous ?_

        ## [](#le-contexte) Le contexte

        “TZCLD: Territoire zéro <mark>chômeur</mark> de longue durée” est une expérimentation sur territoire français menée afin de trouver une nouvelle ma…

```

**Comment by mschoch** [comment]
Good thinking!  That is an excellent workaround for now.  The byte-offsets are recorded from the original, so highlighting works, and in cases I'm aware of, ascii-folding wouldn't affect tokenization, so it works just as well as a token filter.

**Comment by popsUlfr** [comment]
Ok, thanks for confirming that this is viable.

I added a 4th example which puts into one single test file what I've been trying to do by the way. I had an issue with it but rewriting it like that I found out it was because of unreliable language detections so I let the algorithm go further.

https://gist.github.com/popsUlfr/d9233df57643e567f219d3d469e1002f#file-frtestbleve4-go

Basically this like some questionable makeshift analyzer which is supposed to detect the language of text and select the right language analyzer haha
At the character filter stage I try to detect the language with the whatlanggo library, blacklisting the one I found to find any other potential language in the text until the result is unreliable of the max iterations have been reached.

I append the languages to the end of the input. At the tokenizer stage I parse the end to get the languages and cycle through the available analyzers to find matching ones and apply their analyzer function on the input.

Afterwards there's also german special character replacement and finally asciifolding.

This looks a bit sketchy but seems to be logically a way to do this, right ? :D 
For cases where many languages can appear.

Maybe it could be useful to more people ? Might try a pull request unless it's deemed too messy xD

I had another question : can the default fuzziness for string queries be set somewhere ?

Thank you very much for this awesome library.

**Comment by mschoch** [comment]
So, many of the techniques you're describing can be successful, but in my opinion best done outside of bleve, either in the application or some other helper library.  I don't want to discourage you, it's just that if anything we're trying to remove things from bleve where we were too ambitious and didn't have a good solution.  We're moving toward a bleve that is leaner, fewer 3rd party dependencies, but instead, more extension points for people to add these types of things themselves.

**Comment by popsUlfr** [comment]
Yes, that makes sense. Thank you.
