### ISSUE TITLE
search_after issue when documents have identical scores

### ISSUE THREAD

**Issue by tylerkovacs** [blevesearch/bleve#1366]
I think there's still one case where search_after is not working with scoring: when there are multiple documents with identical scores for a search.

Since this is not uncommon in my dataset, I always sort results using `["-_score", "_id"]` for consistent ordering. I'm trying to use `search_after` to paginate through the results, but it doesn't work in this case.

Here's [a branch on my fork that demonstrates the issue](https://github.com/blevesearch/bleve/compare/master...tylerkovacs:tyler/scoring-search-after?expand=1).

And the test result:

```
 $ go test ./test/... -v -run TestIntegration -testnum=18
=== RUN   TestIntegration
    TestIntegration: integration_test.go:49: using index type upside_down and kv type boltdb
    TestIntegration: integration_test.go:71: Running test: alias
    TestIntegration: integration_test.go:71: Running test: basic
    TestIntegration: integration_test.go:71: Running test: employee
    TestIntegration: integration_test.go:71: Running test: facet
    TestIntegration: integration_test.go:71: Running test: fosdem
    TestIntegration: integration_test.go:71: Running test: geo
    TestIntegration: integration_test.go:71: Running test: phrase
    TestIntegration: integration_test.go:71: Running test: sort
    TestIntegration: integration_test.go:150: test error - sort by score, with identical scores
    TestIntegration: integration_test.go:151: test 18 - expected hit 0 to have ID g got d
--- FAIL: TestIntegration (0.47s)
FAIL
FAIL	github.com/blevesearch/bleve/test	0.481s
FAIL
```

Since documents `f` and `g` are identical, the `search_after` query should return the `g` document. But it skips over it an returns the next document (`d`) instead.

This leads me to believe that for sorts that include score, the `search_after` implementation is only looking at the `score` and ignoring other sort fields. Is that possible?

As an aside, I don't have identical documents in my index but I do have documents that return identical scores for certain queries.

**Comment by sreekanth-cb** [comment]
@tylerkovacs , thanks for raising this ticket. 
Looks like this is working as expected.

Scores of relevant documents in descending order are as below,
g - 0.27280626285441445
f -  0.272806 (given in query)
d - 0.21131481344471187

Ie, the actual scores are float values with higher precision like above. But when we pass score values round to 6 decimal positions like 0.272806, this would be treated lesser than the g’s actual score and as per the descending order of scores only document that will be coming after the ‘f’ would be `d`.

Now, if we pass the f’s score value with full precision like  "search_after": ["0.27280626285441445", "f"], then 
As g &  f are equal on scores, document `g` would be in result based on the _id order as it comes after `f`  and document `d` will be in result based on the lower score value than that of f.

[Since d’s score is already coming after that of f’s score in the descending order, it’s _id based order won’t be taken into consideration for d.]

Let us know if this doesn't make sense or i am overlooking something here.

**Comment by mschoch** [comment]
@sreekanth-cb thanks this looks helpful.

I [took a quick check](https://play.golang.org/p/bvtRUFbNWN6), and it looks like JSON Marshal should preserve enough precision in the score (at least for this example value).  So it should be possible for clients to paginate correctly, provided they're careful.  Or am I still missing part of this?

**Comment by sreekanth-cb** [comment]
@mschoch , thats right. JSON marshal should preserve enough precision. 
In this given example, the user was passing only precision upto 6 positions. ref- https://github.com/blevesearch/bleve/compare/master...tylerkovacs:tyler/scoring-search-after?expand=1#diff-13b3ac5576b24ba5e88511ff7608c27bR563

**Comment by tylerkovacs** [comment]
I can confirm this is the case and will close the ticket. Thank you for your hlep!

The issue arose because I was doing suboptimal type conversion when converting the score to a string (necessary because `SearchAfter` is a `[]string`). In my case, I was using:

```fmt.Sprintf("%f", score)```

instead of

```strconv.FormatFloat(score, 'E', -1, 64)```
