### ISSUE TITLE
WildcardQuery and MatchQuery handle `-` differently

### ISSUE THREAD

**Issue by bmhatfield** [blevesearch/bleve#1433]
Hi there,

I'm using QueryStringQuery, and we always append `*` to each user-entered querystring because it emulates prefixing behavior in a way that works well for us.

However, I recently uncovered a case where that causes a problem: when the QueryStringQuery has a [non-boolean `-`](https://github.com/blevesearch/bleve/blob/9ec8f83514c46f72b2fc97e2dc7a5eabef435615/search/query/query_string_parser_test.go#L340) in it.

Without the wildcard, the search routes to `NewMatchQuery`. With the wildcard, the search routes to `NewWildcardQuery`. This is of course expected.

I added a test to be sure:

```go
		{
			input:   "cat-dog*",
			mapping: mapping.NewIndexMapping(),
			result: NewBooleanQueryForQueryString(
				nil,
				[]Query{
					NewWildcardQuery("cat-dog*"),
				},
				nil),
		},
```

What is not expected, is that the MatchQuery version matches documents correctly, while the wildcard version does not:

`cat-dog`: 157 matches
`cat-dog*`: 0 matches

Note that escaping the `-` (as `\-`) does not affect this behavior.

Based upon the highlighting of the results that are returned, it appears that `MatchQuery` is possibly splitting the query into two terms without the `-`, whereas `WildcardQuery` does not.

Given the use of QueryStringQuery here, what should I do? Is this a bug?

**Comment by mschoch** [comment]
I think this expected behavior (need to know which analyzer you're using to confirm).  Assuming it is the standard analyzer, then the text `cat-dog` is indexed as 2 separate terms in the index.  When you run the MatchQuery, we analyze the input, and search for those terms.  However, the wildcard (and regex, prefix, etc) all operate on single terms, they do not analyze the input first.

So, at the moment it appears bleve is working as expected.  There are several things to consider.  Is splitting cat-dog into two tokens appropriate for your domain?  If not, you might need a custom analyzer.  Next, what do you expect your users to type to express this query?  What bleve query produces the correct results?  And, finally, will you need to your own custom query string to build the correct query given the users input?  Probably, but it depends on the details of these answers.

**Comment by bmhatfield** [comment]
Thank you for this response! This makes good sense to me. We are indeed using the standard analyzer.

After reflecting on it a bit, it appears in my domain that splitting `cat-dog` into two terms is sometimes appropriate, and sometimes confusing. I'll study our current corpus and see if I can write a custom analyzer that's a bit more heuristic-based. (one intuition: `c-dog` might be considered one term, but `cat-dog` may intuit as two).

Thanks again. This is a great starting place for me to investigate further. It did not occur to me initially that the query-time issues were because of an index/query misalignment (from the perspective of term indexing).

**Comment by bmhatfield** [comment]
For anyone seeing this, I was able to handle my use-case by adding multiple field analyzers for the field in question. I ended up adding 3-4 to index multiple tokenization/filtering approaches so that different query patterns would be supported.

I did not find any documentation indicating that you can perform multiple field analyses for one field, but experimentation demonstrated that this was indeed possible. The beer_test examples provide some hints.
