### ISSUE TITLE
Set internal row only if changed

### ISSUE THREAD

**Issue by phifty** [blevesearch/bleve#1481]
Hi all,

currently, the mapping is persisted every time an index is initialized. See [here](https://github.com/blevesearch/bleve/blob/master/index_impl.go#L121). This causes a write operation even if the index is just opened and searched. To avoid this unexpected behavior, a write should only be triggered if the value if different from the existing one.

Best regards

**Comment by mschoch** [comment]
The method you have linked to is called during the `newIndexUsing` method, which is only called when creating a new index, not when opening an index.  The corresponding `openIndexUsing` method has no such call to `SetInternal`.

**Comment by phifty** [comment]
You're right. Opening an index doesn't trigger that write operation.

Let me give some background. I've implemented a `kvstore` for badger that takes a badger transaction via the `config` parameter. The purpose is that the index and the items are written and read to/from the same database within the same transaction. The index is created by the call:

    index, err := bleve.NewUsing("", bleve.NewIndexMapping(), bleve.Config.DefaultIndexType, badgerkv.Name, map[string]interface{}{
        "badger_txn": txn,
        "prefix":     indexPrefix,
    })

This call is also done for read-only operations e.g. when the items are searched. Is there a way to open the index with that parameters? If I'm not misled, `OpenUsing` doesn't allow empty paths.

**Comment by mschoch** [comment]
Yeah I don't know what to suggest.  The New and Open methods have a built-in assumption that some meta-data will be stored on disk at the specified path.  The new case will just ignore it if the path is empty, because we reuse this path for our in-memory indexes.  You have found this and started using the New method for both creating new indexes, as well as opening existing ones.

As the new method expects to only be used when creating a new index, it always attempts to store the index mapping.  The open method is closer to what you want, but does not skip the file operations if the path is empty.  And it cannot meaningfully skip those, as we use the loaded meta-data to know which kvstore to use.

It seems your use-case is outside the expectations of the bleve API.  I would be opposed to introducing an option that caused the new method to skip writing the index mapping, as the method is only intended to be used for new indexes.

I think the best option I see is to introduce an option `overrideMeta` honored only by the `openIndexUsing` method.  If you set that to some value, we skip the call to `openIndexMeta` (which is what fails when path is empty), and would instead initialize the important values of the *indexMeta directly from the provided config (things like IndexType and Storage are used later in the method).

I prefer this solution because it keeps the intended usage of new vs open intact.  Would something like this work for you?

**Comment by phifty** [comment]
I guess this solution would work. I'd say, that an empty path is already a good indication that no metadata should be read from disk and no additional option is needed. But I guess that's more a matter of taste.

I found also a workaround to fix my use case. The `KVWriter` in my `KVStore` implementation reads now every value before it's written and checks if it's different. That way the initial write op doesn't hit the database.
