### ISSUE TITLE
About int64 numeric match of NewNumericRangeQuery

### ISSUE THREAD

**Issue by andyzhou** [blevesearch/bleve#1490]
Hi, 

I use beleve in my project develop,  some doc fields are int64 values. 
When i use NewNumericRangeQuery to match big integer value, the int64 value generated by snowflake,  and i convert these value as float64,  matched result failed, but if i use the float64 as begin value and end value as nil, match success.

Here are example code:
```
v := 1322146843034914816

kindFloat := float64(v - 1)

kindFloatEnd := float64(v)

pq := bleve.NewNumericRangeQuery(&kindFloat, kindFloatEnd) //if end value set as nil, match success.

pq.SetField("testField")

boolQuery.AddMust(pq)
```
Can you give me some help, thanks. :)

**Comment by mschoch** [comment]
Inside bleve, numeric values are always represented as a float64.  During the mapping phase, if you're using dynamic indexing for the field (or explicitly choose numeric indexing for that field) we will convert an int64 value to the float64 type.

However, this only works correctly for integers +/- 2^53.   In your example I think you're using a value outside this range.  This means that the value actually indexed is different than the original integer, because float64 cannot accurate represent it.  This could explain why the exact match fails, but searching for a range still finds some match.

**Comment by andyzhou** [comment]
Get it, thank u very much. :)

**Comment by andyzhou** [comment]
Hi, 

I still have some annoying, i use big int as begin value seemed worked, but end value failed.

**Comment by mschoch** [comment]
As I have explained, if you index values outside this range it may not work.  It may work sometimes depending on the exact values used, but cannot be supported to work in all cases.
