### ISSUE TITLE
Implementation of wildcards for search

### ISSUE THREAD

**Issue by gnewton** [blevesearch/bleve#152]
bleve is great but the first thing anyone using the apps I have made says is: "It doesn't do wildcards. I need wildcards for this to work properly". Sigh.

Any chance the priority of wildcard implementation could be moved up? Even if the initial implementation is only "*" and it can only be at the end of a partial term, i.e.  "*foo"  not allowed, but "foo*" allowed.

Could you indicate when wildcards might be implemented?  (Sorry, no pressure!)  :-)

And yes, I owe you a beer!  :-)

**Comment by mschoch** [comment]
It's not particularly hard for us to implement.  It will work much like the simple implementation we have of Fuzzy search today.

My reasons for not making it higher priority are:

1.  Its not particularly fast.  We basically have to have to enumerate (sometimes large) sections of the dictionary to find terms matching the pattern.
2.  In my experience, normal users don't think in terms of wildcards the way developers do.  So, when I talk to other engineers, they always want wildcards, but when I talk to other people, it doesn't come up.  For normal users, having good text analysis and possibly some fuzziness, you can usually match what they're looking for.

All that said, I'm not saying we don't need wildcard support, just that it hasn't been highest priority.

If this is something you wanted to take a crack at here is how I would approach it.

1.  Copy search_fuzzy.go over to search_wildcard.go
2.  Write a function that builds a golang regexp from the wildcard expression.
3.  Change the code to use this function to check terms for a match instead of the levenshtein distance.
4.  Optimization -- if the wildcard pattern has a non-wildcard prefix, we can use this when enumerating the terms to greatly cut-down the number of terms we have to look at.
