### ISSUE TITLE
keyword term query - no result

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1572]
Hi,

I have indexed the data with keyword analyser but when I'm querying, not getting any result.

Here is my mapping:

 ```
       textFieldMapping := bleve.NewTextFieldMapping()
	textFieldMapping.Analyzer = en.AnalyzerName

	keywordFieldMapping := bleve.NewTextFieldMapping()
	keywordFieldMapping.Analyzer = keyword.Name
	keywordFieldMapping.Name = "keyword"

	contentMapping.AddFieldMappingsAt("title", textFieldMapping, keywordFieldMapping)

        subDoc := bleve.NewDocumentMapping()
	subDoc.AddFieldMappingsAt("id", keywordFieldMapping)
	subDoc.AddFieldMappingsAt("title", keywordFieldMapping)
	
	contentMapping.AddSubDocumentMapping("primaryCategory", subDoc)
	contentMapping.AddSubDocumentMapping("categories", subDoc)
	
	indexMapping := bleve.NewIndexMapping()
	indexMapping.AddDocumentMapping("content", contentMapping)
	indexMapping.TypeField = "type"
	indexMapping.DefaultAnalyzer = "en"
```

Now I have structure like below that I have indexed:

```
{
  "title": "This is awesome",
  "primaryCategory": {
    "id": "d4fa2df3-7c98-4417-9f09-b8ff937211a1",
    "title": "Bleve"
  },
  "categories": [
     {"id": "ee3c8074-c444-480a-99f0-d72a3218dff1", "title": "hoffman"},
     {"id": "121ba7ff-38d6-4317-9a62-ff712a3906d1", "title": "alaska"}
  ]
}

```

I want to match the exact title or ID so I have written following query:

  ```
       termQuery := bleve.NewTermQuery("Bleve")
       termQuery.SetField("primaryCategory.title")

       termQuery := bleve.NewTermQuery("Bleve")
       termQuery.SetField("primaryCategory.title.keyword")
       
       termQuery := bleve.NewTermQuery("hoffman")
       termQuery.SetField("categories.title")

       termQuery := bleve.NewTermQuery("hoffman")
       termQuery.SetField("categories.title.keyword")
```

But these are not returning any result. Same I tried with "primaryCategory.id" but no result.
Is there something I'm missing in the mapping or my query is not correct?

Thanks,

**Comment by mschoch** [comment]
The most likely explanation is that we are failing to determine your document's type correctly, and therefore completely ignoring your mapping.  I see you have TypeField configured to "type", but because we have to use reflection to access your documents, `type` is only accessible if your document is actually a map.  If it is a struct, it must be an exported field such as `Type`.  Because of this, you may find using the Classifier (or bleveClassifier) interface more appealing.

So, please review this aspect and let us know if it's still not working.

**Comment by shashank-sachan** [comment]
I actually picked the mapping from bear search example : https://github.com/blevesearch/beer-search/blob/master/mapping.go
I also tried by removing the indexMapping.TypeField = "type" but still it doesn't give any keyword search result.

My struct looks like below:

```
type Content struct {
	Title             string     `json:"title"`
	Categories        []Category `json:"categories"`
	PrimaryCategory   Category   `json:"primaryCategory"`
}

type Category struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

```

**Comment by mschoch** [comment]
So, it's important to understand that mappings have to be designed to work with particular source objects.  In the beer-search example, you'll notice that we unmarshal the JSON into an empty interface, which means the standard library will create a map structure: https://github.com/blevesearch/beer-search/blob/204db6c49802de609443fab595ce08cee5e58b97/main.go#L130-L135

This map structure will have a key "type" with values either "beer" or "brewery", all because of the data inside the JSON.  The mapping that you linked to takes advantage of this to have two different document mapping rules, one for beers and one for breweries.

However, in your example you're using structs (so "type" wouldn't work because of reflection), and also you have no such field anyway.

If you want to have an index mapping that handles Content and Category differently, you'll need to give Bleve some way to know which object you've given it.  Your choices are:

- an an exported field of type string, and give them values that match the type names you use in the mapping, set the TypeField in the mapping to match your field name (again, it must be an exported field)
- add a method `Type() string` or `BleveType() string` and return values that match the type names you use in the mapping

If you add a method, be sure that the correct receiver type is used, specifically that it matches what you pass in to bleve (most likely should be pointer receiver).

If you don't care about types at all, and just want to index everything the same, then forget all of this, don't set TypeField, and simply make set the document mapping you build to be the DefaultMapping.

**Comment by shashank-sachan** [comment]
Thanks @mschoch. Now I understand how it's working.
