### ISSUE TITLE
Query String - bool & sorting

### ISSUE THREAD

**Issue by shashank-sachan** [blevesearch/bleve#1574]
Hi,

Is bool term query and sorting supported in the Query String Query format? I don't find it anywhere in the documentation.

Thanks!

**Comment by mschoch** [comment]
The bool term query is not explicitly supported, because we just index the terms `T` or `F`, but unfortunately this is then incompatible with query strings because they analyze the terms, to they get converted to `t` and `f` respectively and do not find matches.

The query string does not support sorting, because sorting is part of the search request, not part of the query.

In general, we discourage users to rely heavily on the query string query.  It is limited, and we are not longer expanding it's functionality because we believe applications often have conflicting requirements for this behavior.  Your application should parse and build it's own query strings for users, and work with the other structured queries directly.

**Comment by shashank-sachan** [comment]
Thanks @mschoch.
