### ISSUE TITLE
How to filter result by score

### ISSUE THREAD

**Issue by lboquan** [blevesearch/bleve#1583]
Is that possible to filter search results by score? I would like to filter some results that are not accurate enough.

**Comment by mschoch** [comment]
The results are sorted by score descending by default, but bleve does not offer a way to filter by score.  There are a few reasons for this.

First, we have to compute the score for every match anyway, as the last document we look at might have the highest score, so we cannot save any work filtering by score.  Second, we have opted not to add the "min score" filter offered by ES/Lucene as they have noted it isn't particularly useful in practice.  The reason is that scores are not comparable across queries, only within a single result set.  So, it is not possible to say what a good/bad score is before running the query, making effective use of "min score" not possible.

**Comment by lboquan** [comment]
@mschoch Thanks for your fast response. I mention this because the search results are inaccurate,  score can help me to filter out unrelative results. Is there any way to do this without score with pagination? 

By the way, I found bleve.SearchRequest has SetSearchAfter and SetSearchBefore functions. The param is string of slice that makes me confused.  Are there any examples about them?

**Comment by mschoch** [comment]
The quality of the score computed by bleve is not always very good.  That is unfortunate, but it is what we have right now.  If you don't think the score is very good, there is no point in trying to filter by it.

SearchAfter and SearchBefore (can only use one at a time), takes `[]string` because it is expected to be paired with actual Sort value returned by a search result hit: https://github.com/blevesearch/bleve/blob/fc0924f29d818f5f1d1d0d53315ab2913ecd8040/search/search.go#L154

So, the idea is for pagination, you run a search for the top 10 hits using some sort order.  Then you run the same search again, but you take the SortValue of the 10th result from the first search, and pass it in to the second request as the SearchAfter value.  This results an efficient form of pagination, but it has some limitations as well.

Here's an example: https://github.com/blevesearch/bleve/blob/fc0924f29d818f5f1d1d0d53315ab2913ecd8040/test/tests/sort/searches.json#L410-L461

**Comment by lboquan** [comment]
Thanks for your explanation.
