### ISSUE TITLE
Regexp query syntax

### ISSUE THREAD

**Issue by pochuang** [blevesearch/bleve#1588]
I would like to search by NewRegexpQuery for complex syntax. It looks like not all regexp syntaxes are supported. For example, If I search like below, nothing will be returned.

bleve.NewRegexpQuery("title:/(A|B|C).*(D|E|F)/ ")
bleve.NewRegexpQuery("title:/A|B|C|D|E|F/ ")

**Comment by mschoch** [comment]
I don't see any reason that these regular expression won't work, but since you did not provide a complete example here are some possible problems:

- bleve regular rexpression searches operate on the individual tokens indexed, not the entire field, so if you are using a tokenizer that splits the input, you cannot match across these tokens
- most bleve analyzers lower-case the data, and your regular-expression is trying to match capital letters

I would suggest understanding these limitations, and if appropriate, using an analyzer like "keyword" to ensure your regular expressions match against the exact original input.

If you are still having issues, please provide a complete example, which creates an in-memory index, indexes a sample document, and then shows that the search doesn't work.
