### ISSUE TITLE
Can I use HTML highlighting with the default (empty string) field?

### ISSUE THREAD

**Issue by danielhjacobs** [blevesearch/bleve#1593]
I'm sure I'm missing something obvious, but I'm trying to highlight my search results and am running into a problem. I can't seem to find a way to show a highlighted result.

My code:

    package main

    import (
        "fmt"`
        "github.com/blevesearch/bleve/v2"
    )

    func main() {
        mapping := bleve.NewIndexMapping()
        index, err = bleve.New("example.bleve", mapping)
        if err != nil {
            fmt.Println(err)
            return
        }
        data := "DNA does stuff..."

        // index some data
        index.Index("id", data)

        // search for some text
        query := bleve.NewMatchQuery("DNA")
        search := bleve.NewSearchRequest(query)
        search.Fields = []string{"*"}
        search.Highlight = bleve.NewHighlightWithStyle("html")
        search.Highlight.AddField("")
        searchResults, err := index.Search(search)
        if err != nil {
            fmt.Println(err)
            return
        }
        if len(searchResults.Hits) > 0 {
            fmt.Println(searchResults.Hits[0].Fragments[""][0])
            fmt.Println(searchResults.Hits[0].Fields[""])
        }
        fmt.Println(searchResults)
    }

Based on the [documentation](http://blevesearch.com/docs/Highlight%20Matches%20in%20Results/) the output I expected was:

    <mark>DNA</mark> does stuff...
    DNA does stuff...
    1 matches, showing 1 through 1, took 136.685µs
        1. id (0.216978)
	
		    <mark>DNA</mark> does stuff...
		    
But there were no marks around any results, as if I hadn't even included the highlight. My result was:

    DNA does stuff...
    DNA does stuff...
    1 matches, showing 1 through 1, took 136.685µs
        1. id (0.216978)
	
		    DNA does stuff...
    
I see the documentation says the field needs to be Stored and IncludeTermVectors, but since [those default to true](https://blevesearch.com/docs/Index-Mapping/#fieldmappings:fac957943db74e6a57605072a04b8308), I didn't think I had to be explicit about that.

**Comment by mschoch** [comment]
So, in general we discourage people from indexing flat data without field names.  In theory an empty field name is valid, and shouldn't cause problems, but it looks like for some reason it does here.

So, if you'd like a quick fix, I'd suggest changing the data you pass to the Index method to look something like:

```
    data := map[string]string {
        "data": "DNA does stuff...",
    }
```

Then change the other places you reference the field name from "" to "data".  Full update source is:

```
package main

import (
    "fmt"
    "github.com/blevesearch/bleve/v2"
)

func main() {
    mapping := bleve.NewIndexMapping()
    index, err := bleve.New("example.bleve", mapping)
    if err != nil {
        fmt.Println(err)
        return
    }
    data := map[string]string {
        "data": "DNA does stuff...",
    }

    // index some data
    index.Index("id", data)

    // search for some text
    query := bleve.NewMatchQuery("DNA")
    search := bleve.NewSearchRequest(query)
    search.Fields = []string{"*"}
    search.Highlight = bleve.NewHighlightWithStyle("html")
    search.Highlight.AddField("data")
    searchResults, err := index.Search(search)
    if err != nil {
        fmt.Println(err)
        return
    }
    if len(searchResults.Hits) > 0 {
        fmt.Println(searchResults.Hits[0].Fragments["data"][0])
        fmt.Println(searchResults.Hits[0].Fields["data"])
    }
    fmt.Println(searchResults)
}
```

And the output I get is:

```
<mark>DNA</mark> does stuff...
DNA does stuff...
1 matches, showing 1 through 1, took 404.777µs
    1. id (0.216978)
	data
		<mark>DNA</mark> does stuff...

```

Otherwise, someone will have to dig deeper to see where the empty field name is mishandled.  (I have some vague recollection that somewhere in scorch we decided valid field names are non-zero length, but I don't remember where/why or if this relates to this issue directly)

**Comment by danielhjacobs** [comment]
Ok, thank you. I was somewhat worried that would be the answer, as the example application was minimal, and in reality I had build indexes out of so many files that my code had to run overnight, so I'll need to remake the indexes with this new data tonight.

**Comment by mschoch** [comment]
Sorry this is unfortunate, and I think we should update some documentation about this.  While digging into this I found 2 issues:

1. The search operates on the `_all` field by default.  Since this isn't a real field, when we go to highlight the results, we have to consult the field name stored in the location record.  Unfortunately, empty string is a special value meaning there is no other field, the location is part of this field (the normal case for fields other than _all).  So, while we do see the empty string field name here, it is ambiguous in this case and you don't get the expected behavior.
2. Based on the observations of point 1 above, since you just have 1 field, you don't really want to store an `_all` field anyway, as it's just duplicating the data of the original (and only) field.  So, I tried updating the search to scope it to the field "", but this has another problem.  The zero value (empty string) of a field name used to scope a query is also treated as a special value, meaning you don't care which field.  This resets the field to operate on _all again by default.  So again, the empty field name has some special meaning, that gives us the wrong behavior.
3.  Based on the observations of 2 above, I tried one more thing.  Maybe if I changed the mapping's default field to be "", the idea in 2 would work.  Unfortunately, this leads to yet another different crash, because in yet another location the zero value of the field name was used as a special value for an intialization of a map.  And when the empty value is used as a field name, the map isn't properly initialized.

Individually each of these might be fixable, but taken as a whole, it's clear our design did not properly plan to support empty field names.

**Comment by mschoch** [comment]
@danielhjacobs @sreekanth-cb @abhinavdangeti any suggestions on the best place to document this?

**Comment by mschoch** [comment]
Thanks for the suggestions.

Regarding the default field, it is set in the mapping, and controls which field we search when a query does not specify a particular field.  The default value is `_all`.  I'm not sure what you were seeing when you said, "but I was able to figure out it existed by printing searchResults.Hits[0].Fields and seeing [:["text"]]"

Also, I'm not sure if we'll merge it (we have to more formally decide on support empty field name or not), but with this change, and setting the default field to "", I was able to make your code work:

https://github.com/blevesearch/bleve/pull/1594

**Comment by danielhjacobs** [comment]
> I'm not sure what you were seeing when you said, "but I was able to figure out it existed by printing searchResults.Hits[0].Fields and seeing [:["text"]]

Sorry, I was stating what I saw from memory and got it wrong. I meant if you add:

    fmt.Println(searchResults.Hits[0].Fields)

to the code at the top of this thread, map[:DNA does stuff...] prints.
