### ISSUE TITLE
[Bug] - Unable to download bleve

### ISSUE THREAD

**Issue by sujit-baniya** [blevesearch/bleve#1597]
go: downloading github.com/blevesearch/bleve v1.0.14
go get: github.com/willf/bitset@v1.1.10 updating to
        github.com/willf/bitset@v1.2.0: parsing go.mod:
        module declares its path as: github.com/bits-and-blooms/bitset
                but was required as: github.com/willf/bitset

**Comment by mschoch** [comment]
Can you share what command you're running, and in what environment?  Specifically, go version, and are you in a project with a go.mod (share that as well), or something else?

We are aware of the larger issue, but were not aware this also seems to affect 1.x

**Comment by sujit-baniya** [comment]
@mschoch I just tried with following command
`go get -u github.com/blevesearch/bleve`

**Comment by mschoch** [comment]
Thank you, here is complete reproduction:

```
$  cd /tmp
$  mkdir empty
$  cd empty
$  go get -u github.com/blevesearch/bleve
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/willf/bitset v1.2.0
go: downloading golang.org/x/sys v0.0.0-20210603125802-9665404d3644
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/RoaringBitmap/roaring v0.7.1
go get: github.com/willf/bitset@v1.1.10 updating to
	github.com/willf/bitset@v1.2.0: parsing go.mod:
	module declares its path as: github.com/bits-and-blooms/bitset
	        but was required as: github.com/willf/bitset
```

**Comment by mschoch** [comment]
It seems like the renaming of github repositories breaks all old builds referring to the old name.  It will remain broken until we release a new version of bleve 1.x.

Unfortunately the bleve 1.x releases are painful due to circular dependencies.  I will see what we can do, but it the fix may not be immediate.

**Comment by wmolicki** [comment]
So there is no way to install atm? I tried both go get -u github.com/blevesearch/bleve/v2 and go get -u github.com/blevesearch/bleve, same result as above

**Comment by mschoch** [comment]
That is correct, the project is completely broken at the moment.

I tried to push an emergency release out, but it's still broken because we use an older version of Roaring bitmaps which also has his problem.  The latest version v0.7.1 does fix this issue, but that means we have to upgrade a core library from `v0.4.23` to `v0.7.1`, and this will require testing.

**Comment by mschoch** [comment]
OK, I pushed through some more emergency changes.  The following should now work:

```go get -u github.com/blevesearch/bleve/v2```

However, `v2.0.5` was made hastily and has not much testing.  Users with backwards compatibility concerns should NOT upgrade at this time.

**Comment by wmolicki** [comment]
can confirm it works - thanks
