### ISSUE TITLE
Where can i read about scorch?

### ISSUE THREAD

**Issue by hiqsociety** [blevesearch/bleve#1607]
Great work by the way

1. Can scorch use rocksdb backend?
2. Possible to hv unstructured data without pre declaration of struct?

**Comment by mschoch** [comment]
There is very little to read about scorch.  I have given a video about it here: https://www.youtube.com/watch?v=zjG2Y01i3Kk

> Can scorch use rocksdb backend?

No.  Scorch does not use a key/value store for storage.  Instead it uses it's own data-structures, optimized for search, and persists them to disk using a segmented index approach.    

> Possible to hv unstructured data without pre declaration of struct?

I do not understand what you're asking, can you try asking it another way?

**Comment by hiqsociety** [comment]
Need to predeclare struct. I think some search engines don't need to predefined the item types with json etc. Any clues on how to modify this to fit some other use case where unknown new fields will be added without redefining table format?

message := struct{
	Id   string
	From string
	Body string
}{
	Id:   "example",
	From: "marty.schoch@gmail.com",
	Body: "bleve indexing is easy",
}

**Comment by mschoch** [comment]
Bleve's Index method takes `interfacee{}` and it will try to work with any object you pass in.  Some applications, which work with dynamically defined data, unmarhsal JSON into some `interface{}` and then pass it to us for indexing.

NOTE: this works because the mapping process dynamically walks the object using reflection and follows the mapping rules to build up a document object with a flat set of named fields.
