### ISSUE TITLE
How to use stop token map?

### ISSUE THREAD

**Issue by danbiwer** [blevesearch/bleve#1611]
Hi,

I've been trying to use the stop token filter, but am having issues.  I'm trying to follow the example here:
https://blevesearch.com/docs/Token-Filters/

But I suspect this is out of date.

My code is below, and I am getting the error `error building token filter: must specify stop_token_map`

```	
err = mapping.AddCustomTokenFilter("noFilteredTokens", map[string]interface{}{
		"type": stop.Name,
		"tokens": []interface{}{
			"a",
			"b",
			"c",
		},
	})
```

I've also tried creating a TokenMap, but receive the same error.
```
	tokenMap := analysis.NewTokenMap()
	tokenMap.AddToken("a")
	tokenMap.AddToken("b")
	tokenMap.AddToken("c")

	err = mapping.AddCustomTokenFilter("noFilteredTokens", map[string]interface{}{
		"type":           stop.Name,
		"stop_token_map": tokenMap,
	})
```

The [unit test ](https://github.com/blevesearch/bleve/blob/v1.0.14/analysis/token/stop/stop_test.go)creates a registry.Cache and defines a new token map from there.  Are there no convenience functions around creating a stop token filter or am I missing something?  Any tips would be appreciated.  Thanks.

**Comment by mschoch** [comment]
Unfortunately, the the index mapping was designed with a focus on serialized components, which are referred to by string names.  This is useful for serializing things, and referring to them outside of code at runtime, but much of this is not very idiomatic Go.

With that, the error message you see can be found here: https://github.com/blevesearch/bleve/blob/ae28975038cb25655da968e3f043210749ba382b/analysis/token/stop/stop.go#L59  And we can see that the parameter "stop_token_map" needs to be a string reference to named token map, not a direct Go pointer to a token map as your code creates.  (obviously the documentation is also wrong, and seems to refer to some outdated way of configuring the stop tokens)

So, you would instead first build a named token map using

```
mapping.AddCustomTokenMap("customTokenMapName", customTokenMapConfig)
```

The `customTokenMapConfig` would look like this: https://github.com/blevesearch/bleve/blob/ae28975038cb25655da968e3f043210749ba382b/analysis/token/compound/dict_test.go#L107-L110

NOTE: the unit tests are manually using the registry/cache, but you do not need this as the mapping handles this.

Then once you've added the custom token map, as described above, you would refer to it's name when configuring the `stop_token_map` parameter.

As you can see, creating a custom mapping manually with Go code is quite ugly.  And that is because we (incorrectly) assumed users would simply pass in a blob of JSON.  In the updated design of bluge, we have eliminated the mapping entirely.

**Comment by danbiwer** [comment]
Thanks for breaking it down for me!  Looks like AddCustomToken() map was what I was looking for.
Putting it all together, I get

```
package main

import (
	"github.com/blevesearch/bleve"
	"github.com/blevesearch/bleve/v2/analysis/tokenmap"
)

func main() {

	mapping := bleve.NewIndexMapping()

	tokenMapConfig := map[string]interface{}{
		"type":   tokenmap.Name,
		"tokens": []interface{}{"factor", "soft", "ball", "team"},
	}

	err := mapping.AddCustomTokenMap("customTokenMap", tokenMapConfig)

	if err != nil {
		panic(err)
	}

}
```

Unfortunately, this returns an error `no token map with name or type "custom" registered`.  Is this a bug or user error?

**Comment by mschoch** [comment]
@danbiwer I just copy/pasted your example locally with one change (NOTE that the bleve import should also be /v2):

```
"github.com/blevesearch/bleve/v2"
```

When I do this, it builds and runs without error.
