### ISSUE TITLE
is bleve advisable to be used as a primary datastore e.g. mysql without logging?

### ISSUE THREAD

**Issue by hiqsociety** [blevesearch/bleve#1616]
1. can bleve be used as a sql datastore? what are the caveats / limitations to look out for other than no replication features for the moment
2. how do i delete entries? or do replace?

**Comment by mschoch** [comment]
I will try to answer your questions, but from my perspective you have used some imprecise terms, which I will also try to clarify my usage of.

1.  Bleve cannot be used as a `sql` datastore, because it has no support for SQL.  But, in the title of this issue you asked about `primary datastore`.  Bleve can be used for this, but we generally don't recommend it.  The reason is that it isn't the main purpose of the library.  So, whenever we have to make a trade-off between a better index or a better data store, we will always choose the index because that is our focus.  NOTE:  if you choose to use Bleve as a primary data store, you must take additional steps to use bleve in a particular way.  Specifically, you must ensure that all your data has been persisted to disk (not using `unsafe_batch` option, and always waiting for indexing methods to return without error).
2. You delete items using the `Delete()` method: https://github.com/blevesearch/bleve/blob/fc8a89fe87aeb8824dbdf8b518a1049da5314c4f/index.go#L213 and you replace items using the `Index()` method: https://github.com/blevesearch/bleve/blob/fc8a89fe87aeb8824dbdf8b518a1049da5314c4f/index.go#L212  Indexing an item always replaces any previous item with the same identifier.

**Comment by hiqsociety** [comment]
ok thx.
