### ISSUE TITLE
unable to match word "any" in array using regex query string search

### ISSUE THREAD

**Issue by fanadol** [blevesearch/bleve#1638]
Hi, I am unable to match word "any" in my array using regex

Here's the example:
```
package main

import (
	"log"

	"github.com/blevesearch/bleve/v2"
)

type People struct {
	ID   string   `json:"id"`
	Pets []string `json:"pets"`
}

func main() {
	mapping := bleve.NewIndexMapping()
	index, _ := bleve.NewMemOnly(mapping)

	p1 := People{ID: "1", Pets: []string{"dog", "cats", "any"}}
	index.Index(p1.ID, p1)

	queryString := "+pets:/(any)/"

	query := bleve.NewQueryStringQuery(queryString)
	search := bleve.NewSearchRequest(query)
	result, err := index.Search(search)
	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("%+v\n", result)
}
```

It will yield no result. I am new in bleve, Is there anything that I missed ?

**Comment by iredmail** [comment]
Did you try `bleve.NewMatchQuery("any")`?

**Comment by fanadol** [comment]
I am afraid i cannot use that. because i need to do some regex, for example `"+pets:/(cat|any)/"`.

**Comment by fanadol** [comment]
For additional information, if I use `"+pets:/(dog)/"` , it will match.. but if I use `"+pets:/(any)/"` it will not match.

**Comment by abhinavdangeti** [comment]
@fanadol It's because of the analyzer that's in play. You're not setting any specific analyzer for your mapping, so the default analyzer that's being picked up is **standard**.

The standard analyzer will not index the term "_any_" - it's a stop word (similar to english).

I'd recommend using the "simple" analyzer or something more applicable. You can test out some of the analyzers' functionality here - http://bleveanalysis.couchbase.com/analysis.

```
import (
	"github.com/blevesearch/bleve/v2/analysis/analyzer/simple"
)

...

func main() {
    mapping := bleve.NewIndexMapping()
    mapping.DefaultAnalyzer = simple.Name
    ...
}
```

**Comment by fanadol** [comment]
aha, it works now.. I don't know if we can adjust the analyzer.
Thanks @abhinavdangeti
