### ISSUE TITLE
How to load already indexed data in bleve.index object without creating a file

### ISSUE THREAD

**Issue by leenalast9** [blevesearch/bleve#1656]
1. We store indexed document in a **DataBase**
2. To load the indexed document , we need to create file and use **bleve.open()** function
3. We can't use this option as we have many files and it gives error **"Too many open files"** (note: we are already closing files after it's use)
4. What is the other to load already indexed data (which is in memory variable) without creating a file.
5. I thought **bleve.NewMemOnly** will be useful for us. But doesn't look like as it is for unindexed data. **We already have indexed data and we want to load it in bleve.index object without creating a file**

**Comment by abhinavdangeti** [comment]
Bleve will **ONLY** work with index files that were created with it.
So you'll need to tell us more about your indexed documents.

The mem-only option allows for you to use all of bleve capability without actually storing content on the disk - for which you will still need to import your "indexed content" into a bleve.Index.

**Comment by leenalast9** [comment]
1. Yes we have one cron job which create indexes using store files.
2. we store the contents of above "store" file in DB
3. We have around 500 indexed documents = 500 rows in DB
------------------------------------
1. We have one http handler which serves the search request
2. when request comes, we load this indexed byte data from DB
4. store in "store" file
5. create "metadata" file
6. give this folder to b**leve.open(index_folder)** which return **bleve.Index object**
----------------------------------------------
I was thinking, can we avoid 3rd and 4th step (which we need to do 500 times) and have something like this:

**index = bleve.open(indexed_data, config_data)
          bleve.open(byte[], byte[])**

**Comment by abhinavdangeti** [comment]
I'm still a bit confused on what you're attempting to do here.

- If you're already using a bleve.Index reference to index/store content, then - why not use the same bleve.Index object to serve the search request as well?
- Separately, a bleve.Open(..) over a valid index path shouldn't create any new file.

**Comment by leenalast9** [comment]
As I explained. We have two separate processes.


**PROCESS1**
1. Creates the index. 
2. Ir saves contents of "store" file in Database (which is nothing but indexed data)
-----------------------------------------------------------------
**PROCESS2**
1. It serves search result. It is oblivious to Index object created by first process. It's altogether different process. (PROCESS1 and PROCESS2 are different parallel processes)
2. It loads indexed byte data from DB (which was created by process-1)
3. It create "store" file and save this data in this file
4. It creates "metadata" file
5. give this folder to bleve.open(index_folder) which return bleve.Index object
----------------------------------------------------------------------------

I was thinking, can we avoid 3rd and 4th step (which we need to do 500 times) and have something like this:

index = bleve.open(indexed_data, config_data)..... so that we don't need to create files in 3rd and 4th step.
            bleve.open(byte[], byte[])

**Comment by sreekanth-cb** [comment]
hey @leenalast9, 

there might be some misunderstanding between your use case/requirement as against the right use of a bleve index.

Few thoughts around your approach,

-You could have a single bleve index that indexes a whole lot of data against different rows (all the rows) in your DB and use that single/bunch of index(es) to serve the Process2/queries. Perhaps, skip the use of Database altogether if this is an index once and query thereafter use case? ( but I guess that isn't the case and hence you resorted to the use of DB here)

-What if you store the index store folder path as well in your DB in each row so that you could load your bleve index directly from that path rather than creating the folders, copy the index contents and then load it every time. 
Even if both process1 and process2 exist on different nodes, you could still set up the index and update the path in your DB once in the read paths for the local node.

**Comment by leenalast9** [comment]
Hi @sreekanth-cb 
Yes this makes sense to me. Thank you so much.
