### ISSUE TITLE
v2.3.5 termMatch.BytesRead undefined

### ISSUE THREAD

**Issue by wangjiepower** [blevesearch/bleve#1754]
github.com\blevesearch\bleve\v2@v2.3.5\search\scorer\scorer_term.go:201:27: termMatch.BytesRead undefined (type *index.TermFieldDoc has no field or method BytesRead)

**Comment by Thejas-bhat** [comment]
@wangjiepower, can you please confirm if you're using bleve_index_api version 1.0.4 (which is used in bleve v2.3.5)? This is because, this problem could occur if you end up using bleve_index_api versions other than that (perhaps because of independent updates of the two packages).


Also, I did a fresh a download of the v2.3.5 bleve source code and ran a `go test ./...` in it, everything looks fine over there and that must have caught any such issues over there.

**Comment by wangjiepower** [comment]
I use bleve_index_api version 1.0.5 , as you said , I upgrade two packages. and change bleve_index_api  back to 1.0.4 ,it worked ,ths

**Comment by Thejas-bhat** [comment]
awesome
