### ISSUE TITLE
How to search for words like "C++" or "C#" by bleve? 

### ISSUE THREAD

**Issue by TruthHun** [blevesearch/bleve#1790]

**Comment by Thejas-bhat** [comment]
Just a bit of background on some search and indexing stuff, the question you've raised boils down to the choice of analyzers. This is because let's say you index a field in a document with a dutch analyzer (nl), it will apply the dutch specific rules to the text while performing the analysis and the resultant tokens are indexed. While querying against this same field, bleve applies the same dutch analyzer on the query you've passed and the resulting tokens from that analysis is the actual thing used to search on the indexed text.

I believe if you use existing analyzers, which by default include the unicode tokenizers, you'll end up removing the ++ and # suffixes at both the indexing and querying time and won't be able to search c++ intact. So, perhaps using a bit simpler tokenizer such as whitespace would help out. 

What you'd have to do is basically, create a custom analyzer with the tokenizer set as whitespace and any set of token filters that you'd want for the text you're indexing and querying. Using this custom analyzer on the field you're indexing would allow you to search for c++ and c# on that particular field in its entirety. 

I'd highly recommend using this bleve analysis wizard
 https://bleveanalysis.couchbase.com/analysis
to try analysing the text and see what are the tokens emitted at indexing and querying times to get a better sense as to what is stored in the index and what is actually searched while querying. You could also try creating custom analyzers such that the emitted tokens look like the way you want them to be and use that exact same analyzer in your application.
