### ISSUE TITLE
KVStore's should keep own copy of value bytes on Set()

### ISSUE THREAD

**Issue by steveyen** [blevesearch/bleve#181]

**Comment by mschoch** [comment]
Also, lets review inmem and cznic/b for the same potential issue.

**Comment by steveyen** [comment]
Keys should be stable and immutable, so shouldn't need copying.  This change copies incoming value bytes KVStore gtreap: commit f92ab13

**Comment by steveyen** [comment]
Updated issue title to be more than just gtreap, as this affects all KVStore's.

**Comment by mschoch** [comment]
I'm actually rethinking this.

It seems to me that at the top-level bleve package, users data that they ask to be indexed should be safe.  This implies that we should be creating copies prior to text analysis.  Because under no circumstances should we either mutate users data, or retain a reference after Index()/Batch Execute() complete.

I'll leave these changes for now, as I'd like to put tests in place to ensure we adhere to this.
