### ISSUE TITLE
Getting the index name from the search result

### ISSUE THREAD

**Issue by dustinwtf** [blevesearch/bleve#196]
I am running the MultiSearch query and I would like to know if there is a way to get the index name from the search result. That way I can distinguish what is what from the merged results.

**Comment by mschoch** [comment]
Forgot to reply to this earlier.  I agree this is an oversight.  The results should provide an indication of which index they came from.

**Comment by mschoch** [comment]
I think where there is agreement is that each search result hit should include the name of the index it came from...

But, it turns out one of the problems we have is that indexes don't have names.  As we're a library first and foremost, the index object need not be named, apps simply have references to them.

This same problem came up in the bleve-explorer app which then needs to map user supplied names to indexes.  It does so by externally managing a map of index names to index instances.

I can see a couple of options.

1.  MultiSearch could operate on a map of indexes (keyed by name) instead of a slice.  On the surface this seems simple and solves the problem, but it would probably also need to be extended to IndexAliases to really be useful.

2.  Add a function

Name() string

to the Index interface.  By default, it could be some identifier returned by the KV store (often a filename).  But we'd also let application change it to whatever they want.  Bleve itself would never use it for anything, it would exist solely to help the application refer to it externally.  Bleve would also offer not guarantee that these names are unique, that would be up to the application.  When returning the results Bleve would include the index name in each result.

I'm leaning towards option 2, but would like feedback from @steveyen since this would seem to be applicable to cbft as well.

**Comment by dustinwtf** [comment]
I agree with you there. I like option #2 as well. It really doesn't need to be complicated, just a way for the applications to identify where the result came from.

Thanks!

**Comment by mschoch** [comment]
Support for this was recently added: d73beac3b983964945617485275605a9ca1d5eec
