### ISSUE TITLE
Possible stemming issues

### ISSUE THREAD

**Issue by romanoff** [blevesearch/bleve#230]
Code to replicate issue:

```
package main

import (
	"fmt"
	"github.com/blevesearch/bleve"
)
type ArticleData struct {
	Name string
	Content string
}

func main() {
	// open a new index
	mapping := bleve.NewIndexMapping()
	index, err := bleve.New("", mapping)
	if err != nil {
		fmt.Println(err)
		return
	}
	index.Index("id1", ArticleData{Name: "About", Content: "about text about"})

	query := bleve.NewMatchQuery("about")
	search := bleve.NewSearchRequest(query)
	searchResults, err := index.Search(search)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(searchResults)
}
```

Any ideas why this code returns "No matches"? If I search for "text", it finds this article. Also just for fun I searched using "about" word through bleve tutorial and didn't find any results either (although that might be because that word was never used)

**Comment by mschoch** [comment]
The default analyzer used is "standard".  The standard analyzer removes English stop words.  The default English stop word list includes "about".

https://github.com/blevesearch/bleve/blob/master/analysis/language/en/stop_words_en.go#L234

If you don't want stop words removed, you can use the "simple" analyzer instead of "standard".  Or if you want to curate your own stop word list, perhaps not containing "about", you can configure that by assembling the pieces yourself (ie, build an analyzer just the "standard" but reference your own stop word list)

**Comment by romanoff** [comment]
Thanks a lot for quick response!
