### ISSUE TITLE
doc search on the wiki doesn't link to search results

### ISSUE THREAD

**Issue by glycerine** [blevesearch/bleve#232]
instead, the doc search hits always direct to "create new page" on the github wiki.

In effect, no documentation is available for bleve at the moment.

:-(

**Comment by mschoch** [comment]
Ah, sorry for the confusion.  The documentation has been moved out of the wiki and onto the website.  We never got very many outside contributions, and the site gives us more options for organizing the content.

Please start here:

http://www.blevesearch.com/docs/Home/

I had replaced the wiki home page with an explanation of the move.  Was there another link somewhere else that I missed?

**Comment by glycerine** [comment]
Hi Marty,

Thanks for the fix and the pointer to docs.

This link still shows the issue:

http://wikisearch.blevesearch.com/search/

If I type in "syntax" I'll get a single hit back. The search result page is

http://wikisearch.blevesearch.com/search/?q=syntax&p=1

whose single search hit links to 

https://github.com/blevesearch/bleve/wiki/Query-String-Query

which is just a "Create new page" on the github wiki.

**Comment by mschoch** [comment]
Thanks, I think I'll change that to just be a redirect to the new search on the website.

**Comment by mschoch** [comment]
It should be redirecting now.

**Comment by glycerine** [comment]
Nice. Much better now. 

If I may ask, what backend database are you using to host your wiki? 

I'm actually interested in building a wiki that is integrated with Acceptance Test Driven Go code, so I'm curious how golang-centric wikis and full-text search engines store their pages.

Thanks!

Jason

**Comment by mschoch** [comment]
We don't actually operate a wiki.  Previously we were using the github wiki, but it has a lot of limitations.

The website is built as a static site using Hugo - https://gohugo.io/

Since it generates a static site, we host it using github pages.

The source for the site is here:

https://github.com/blevesearch/blevesearch.github.io-hugo

And the generated site is here:

https://github.com/blevesearch/blevesearch.github.io

Now, since this is just a static site, it doesn't offer search out of the box.  But, since our project is a search library we wanted to dogfood our own code.  So we index the hugo content using a bleve command called hugoidx.  And we host a small wrapper program that only serves read-only queries to the index called bleve-hosted.

I wrote up a blog post about the integration here:

http://www.blevesearch.com/news/Site-Search/

Its still a little bit experimental, but it seems to be working for us.

**Comment by glycerine** [comment]
@mschoch very nice. thanks for the explanation.
