### ISSUE TITLE
Speed-up boltdb bulk loading with NoSync=true

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#240]
Hello,

On my small benchmarks (~17000 json documents), setting NoSync=true in boltdb backend makes reconstructing the index twice faster than without. This should definitely not be the default, but I see value in a configuration entry to do this programmatically when tinkering with index mappings or rebuilding indexes from scratch.

Thoughts?

**Comment by mschoch** [comment]
My preference is actually to make calls to Index and Batch have no guarantees, and have separate Commit method.  This is a bit more like lucene anyway, and there are a lot of use-cases where you don't need any guarantees, since you can often just pickup where you left off and keep going.

But, it would be a big change to the semantics of the API.  I've been trying to tackle these big changes like one at a time and get buy-in from the community.  This change was still further down on the list though.

**Comment by mschoch** [comment]
A simple solution we could implement today without breaking anything would be to support it as a config option when you open the store.  This would allow using nosync or equivalent in a kvstore during development, then turn it back on for production.  Or a bulk loading function/tool could open with the flag, then close/reopen when done.

Would something like that work for now?

**Comment by pmezard** [comment]
That is what I had in mind.

What kind of compatibility rules do you have on store options? And what should happen when passing ignored options (currently nothing, but IMHO it does not help with handling library updates)?

If flags can be changed, and the code is made to fail when encountering unknown flag, I would choose something accurate like "nosync", rather than something vague giving more freedom with compatibility like "bulk".

**Comment by mschoch** [comment]
The problem is that different kvstores have different options.  Its tempting for us to try and standardize on some with common meaning, but I think thats a mistake.  The approach I've been taking so far is to use names that are as precise and meaningful to that particular kv store.  So, boltdb would get a flag, "nosync".  LevelDB,RocksDB,etc don't have a "store" level corresponding option, so, it would probably make sense to also support "nosync" but there we use it to set a per-mutation flag.  ForestDB on the other hand has 4 sync options and they call it durability, not just boolean true/false, so there we'd name it "durability", and support "string" values.

Right now you're correct we just ignore any options we don't understand.  Occasionally that has bitten me when I have a typo and don't realize I'm not using the option I thought.  I could be persuaded that its better to return an error if you feel strongly about it.

**Comment by pmezard** [comment]
OK, so should I make a PR with the "nosync" option for BoltDB?

As for rejected unknown options, I would have done that from the start. I do not know enough about past options and client compatibility expectations to know if such a change would be acceptable now. Your call.

**Comment by mschoch** [comment]
Sure if you want to submit a PR for that it should be pretty straightforward.

OK, regarding unknown options we'll keep the same behavior for now.  I'd like to post it to the group, give people a week or so to raise objections and/or update code to expect errors.

**Comment by pmezard** [comment]
Merged.
