### ISSUE TITLE
doc query string example is incorrect, or query string builder is buggy

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#258]
Hello,

As mentioned in https://github.com/blevesearch/bleve/pull/257 , the query string example in:

  http://www.blevesearch.com/docs/Query-String-Query/

is incorrect. `+description:water -light beer` is really equivalent to `+description:water -light +beer` because the query string builder sets minShould to 1 instead of 0.

I do not know what is the correct fix. Current behaviour is necessary for "foo bar" like queries, to have at least one among many. But it is confusing when adding must/mustNot conditions.

Maybe fixing the documentation is enough.

**Comment by mschoch** [comment]
Yeah, I think minShould was 0 before, but changing it to 1 fixed compatibility with a different class of queries.  I'd like to review how Elasticsearch rewrites a few of these queries to see what we should do.

**Comment by mschoch** [comment]
This issue has come up now in CBFT now as well: https://issues.couchbase.com/browse/MB-17304

We now know that our behavior differs from ES in queries like the one above.  I still have to do some more testing to see how they handle queries with all SHOULD clauses.

**Comment by pmezard** [comment]
Nice to hear. I am reading a book on ES right now, and my understanding is:
- if len(must) == 0, then minshould == 1 (assuming len(should) > 0)
- otherwise minshould == 0

**Comment by mschoch** [comment]
So, in my additional testing, queries like "foo bar" still work, because the individual term searchers only produce results for things that match at least one of the terms.  So, even with minShould = 0, and a handful of SHOULD queries it still seems to work as expected.

I'm going to flip the default back to 0.  I've added a testcase for the type of query we fix.  If we find another class of queries that are actually broken in the future we'll revisit it.
