### ISSUE TITLE
Use open bolt handle to back bleve

### ISSUE THREAD

**Issue by barakmich** [blevesearch/bleve#259]
Hey! So suppose I'm already using bolt and would love to add a text index using bleve. Is there a way that one could use a pre-opened bolt handle and a bucket name as options passed to bleve.New() or bleve.Open()?

**Comment by mschoch** [comment]
This is possible, but it would come with a lot of caveats.  In the end we decided we didn't want to clutter the API supporting things like this that were uncommon.

What you can do today is, first create/open a Bleve index that uses Bolt.  And then you can get access to the underlying KVStore using the Advanced() method.  This method just leaks handles to the underlying index implementation and kvstore.  From there, you could type assert the kvstore reference to the Bolt type, and access the raw Bolt handle.  Bleve still "owns" the handle, and will be the one to try and close it later on, but if you're careful and know what you're doing you could do other things with the same handle.  It's not exactly what you're asking for, but could be used to the same end result if the code was organized differently.

One of the reasons its hard for us to do it the other way around is that there are some KVStores where we need to perform operations on the KVStore before we open it.  For example, in RocksDB we have to install the native merge operator prior to opening it.  Even though this doesn't apply to BoltDB, since we're going through a common abstraction layer, everyone inherits that benefit/limitation.  So, we'd have to find a way around that.

**Comment by barakmich** [comment]
Yeah, looking at the code, the closest I would find would be to have a special filename "bolt handle" or similar, and pass it as a config option to NewUsing/OpenUsing -- which I agree is messy.

Perhaps the easier thing is just to create a directory :) Thanks!
