### ISSUE TITLE
consider use of io.Reader instead of []byte in analysis API

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#276]
Idea comes from this tweet: https://twitter.com/tsenart/status/663733506351198209

**Comment by pmezard** [comment]
It sounds nice when comparing to common library APIs, but does it help in analysis/indexing case? AFAIK, analysis operates on input documents and on query strings. I do not think io.Reader brings much for query strings. And when dealing with documents, they are passed as a combination of fields. Using io.Reader sounds burdensome too. 

Would it improve analysis API? I don't know but it would certainly make some algorithms harder to write.

Do you have details about the actual use case? Do they deal with large documents?

**Comment by mschoch** [comment]
Yep, I agree that was my first reaction as well.  We only had a few minutes to discuss this in person, and when I tried to explain the points you mentioned it sounded like we both weren't understanding each other.  So, I wanted to capture it here and followup later.  I agree we need more information, I'll try to reach out and see if we can get it.

**Comment by Shugyousha** [comment]
On Tue, Nov 17, 2015 at 08:40:11AM -0800, Patrick Mézard wrote:
> It sounds nice when comparing to common library APIs, but does it help in
> analysis/indexing case? AFAIK, analysis operates on input documents and on
> query strings. I do not think io.Reader brings much for query strings. And when
> dealing with documents, they are passed as a combination of fields. Using
> io.Reader sounds burdensome too.

Using io.Reader is a good idea if you either

1. expect to be able to use io.Reader interface values for input or
2. expect that you will output io.Readers for use with other packages or
   within your application.

I looked into the Analysis chain somewhat with that perspective and I
too think it does not make sense to use the interface in this case. The
reason being that neither point 1 or 2 above apply.

Since the index.Index method is reflect based it cannot reasonably
easy make use of io.Reader. To change the Analysis queue itself to use
io.Reader is also problematic since we potentially have to store the
field values (for TextField) for which we would have to save the bytes
anyways. The same is true for the tokenization and CharFilter processing
stages which should be possible to change but we would just end up
getting the bytes out of the readers anyways because the tokenizers
(as far as I can tell) do not take io.Readers but []byte as input.
Changing that would be possible for the internal ones but I don't think
there would be an advantage for the bleve users.


> Would it improve analysis API? I don't know but it would certainly make some
> algorithms harder to write.
> 
> Do you have details about the actual use case? Do they deal with large
> documents?

I would be interested to hear about their use cases as well because I
can't see the utility at the moment.

**Comment by mschoch** [comment]
I think there is consensus that this doesn't improve anything useful for bleve 1.x, we can reconsider when designing bleve2 api.
