### ISSUE TITLE
phrase queries silently return nothing when applied on fields without term vectors

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#280]
Phrase queries only work if target field stored its terms vectors. Otherwise they return no result. I think they should fail with a clear error message. Or at least, it should be clearly stated in NewPhraseQuery and NewMatchPhraseQuery documentations.

What do you think? (I have not investigated composite fields).

**Comment by pmezard** [comment]
Another approach is to turn it into ConjunctionQuery(terms) if the terms vector is not stored. This is what I will do in my application. I am not sure I would want that to happen silently.

**Comment by mschoch** [comment]
I certainly agree on the documentation.  Its just phrase search right now, but in the future the same will be true of span/near queries as well.  

I'm less sure about making it an error.  As you alluded to, the composite fields become problematic, as they can compose the contents of fields both with and without term vectors.  A phrase search on the composite field in this case can still make sense.

I see the appeal, because in this case it seems like we can figure out that there clearly is a problem, but I worry that this is actually a larger class of problems, and we set an expectation we can't always meet.
