### ISSUE TITLE
Make it easier to analyze text for a given field

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#282]
I tried to implement something similar to matchQuery but requiring all analyzed terms to be matched instead of only one. But there is a missing bit in IndexMapping API preventing me to do that: AnalyzeText() let me apply an analyzer by name, but there is no way to get the analyzer mapped to a field.

What do you think of either:
1- Exposing analyzerNameForPath(), maybe as GetFieldAnalyzer(field) string
2- Adding an AnalyzeFieldText(field, text)

[1] seems globally more useful.

**Comment by mschoch** [comment]
I think I'm OK with [1], though I would suggest the signature FieldAnalyzer(field) string, as Go recommends leaving the Get prefix out of getter method names.

There is one big caveat.  If you have the same field names in multiple types and configure them differently, the analyzer you get is undefined.  Further, since we keep them in a map and Go randomizes iteration, you may get different results over time from the same mapping.

This is a much larger issue, but I mention it here because it does affect usage.
