### ISSUE TITLE
Performance ?

### ISSUE THREAD

**Issue by kk00ss** [blevesearch/bleve#288]
Are there any benchmarks of bleve vs lucene and other engines ?
I've made my own and I'm not happy with performance it takes more than 2s to search set of 1M documents with at most two terms in them, and only 1/8 of them answer this query - I've performed same benchmark with Lucene and it took about 7 milliseconds. Have you considered evaluating/integrating Groonga/Zettair/Sphinx/CLucene search engines into Couchbase ? All of them claim to be faster than Lucene (and there are plenty of benchmarks). My interest was tinkering with bleve's storage architecture - but with such a performance it just doesn't make sense. My guess is that doing singe read of a compressed block is much faster than iteration over items one by one. To my knowledge Xapian uses B-trees as a storage and they went from using such a model (B-tree item for a field-term-document) to storing blocks in B-tree - benchmarks I saw were outdated, but that model seems to be still a bit slower than Lucene. BTW storage space used by bleve also seems bigger. In defence of Bleve - architecture is much simpler (probably because it's younger project) and code is easier to read. 

Here is my code:
```
// You can edit this code!
// Click here and start typing.
package main

import (
//	"github.com/libreoscar/lmdb"
	"github.com/blevesearch/bleve"
//	. "github.com/blevesearch/bleve/search"
	
	"fmt"
//	"strconv"
//	"time"
)
func main() {
    // open a new index
	//mapping := bleve.NewIndexMapping()
    //index, err := bleve.New("example.bleve",mapping)
	index, err := bleve.Open("example.bleve")
	
    if err != nil {
        fmt.Println(err)
        return
    }
	/*
	b := index.NewBatch()
	N := 1000*1000
	MaxNumOfLeadingZeros := 5
		for j:=0; j < N; j++ {
			text := "Hello"
			if(j % 8 == 0){
				text += " world"
			}
			data := struct {
		        Name string
		    }{
		        Name: text,
		    }
		    // index some data
			numberOfLeadingZeroes := MaxNumOfLeadingZeros
			if(j != 0){ 
				numberOfLeadingZeroes+=1
			}
		    for tmpJ := j;tmpJ != 0;tmpJ /= 10 {
				numberOfLeadingZeroes -=1
			}
			pref := ""
			for z:=0; z < numberOfLeadingZeroes; z++{
				pref += "0"
			}	
			//index.Index(pref+strconv.Itoa(j), data)
			b.Index(pref+strconv.Itoa(j), data)
			if(j % 1000 == 0){
				fmt.Println("j = ",j)
				index.Batch(b)
				b = index.NewBatch()
			}
		}
	index.Batch(b)
	*/
    // search for some text
    query := bleve.NewMatchQuery("Hello world")

    search := bleve.NewSearchRequest(query)
	search.Size = 10
	for x:=0; x < 100; x ++ {
    	searchResults,err := index.Search(search)
   		if err != nil {
   	    	fmt.Println(err)
   	    	return
   		}
    	fmt.Println("Naive search ",x)
		fmt.Println(searchResults.Took)
	}

	

}

}
```

**Comment by mschoch** [comment]
The benchmarks we're working on are located in the [bleve-bench](https://github.com/blevesearch/bleve-bench) repository.  We're in the process of setting them up so that we can produce nightly charts that look similar to the [lucene nightly benchmarks](https://people.apache.org/~mikemccand/lucenebench/)  As soon as this is ready, repeatable and published at a public URL we'll share it with everyone.

We know that right now the performance is nowhere near Lucene, which is why we don't make any claims about performance.

There is nothing obviously wrong in the code above, but I would need to see the Lucene version to draw conclusions.  One frequent difference is that we store fields and index the term vectors by default, whereas Lucene does not.  That makes some difference, but not a lot.

The only other thing I can add is that we're currently working on a new indexing scheme, its available on the firestorm branch.  It's not usable yet, but that is what I'm working on.  Even still, that won't address your immediate concerns as we're focusing on indexing throughput first, not search performance.

**Comment by kk00ss** [comment]
I don't have Lucene version sources at the time, but it was pretty straight forward. Thanks for quick answer.
