### ISSUE TITLE
Question regarding usage in a cqrs style system

### ISSUE THREAD

**Issue by joeblew99** [blevesearch/bleve#306]
So I have a ton of data.
It comes in and I write it to boltdb - ingestion phase.
 I save it in a json structure ready for reading, not writing. Hence cqrs.
I also get Bleve to parse and index it.
E.g.
Users have products, and users have accounts types. 
Products have images too.

The clients make requests and I query your system in Bleve, and it gives me back an I'd to the data I stuffed into boltdb in the first place.

A user edits the data, and it goes back to the original ingestion phase.

Is this the basic way to use bolt and bleve for business data ?

Are there any examples ?

Did I pretty much get it right in terms of. Qrs being a good match for boltdb and Bleve ?

How to scale boltdb. I guess I need to do a consistent hash and break it up to many boltdb.
But then I have to make sure queries don't span across more than one dB, otherwise it gets messy ?

Sorry about the high level questions but we'll so many choices these days also I am wanting to use a 109% golang stack - its a disease :)

Thanks in advance.

**Comment by mschoch** [comment]
I'm not that familar with CQRS, just read the first few paragraphs to know what you were talking about.  But the sequence of operations you describe sounded OK to me.  One thing you may want to do is disable storing fields in Bleve, since (as described above) you'll only be using the ID to go back to the original data stored in BoltDB.

I don't know of any examples that combine bolt and bleve for business data.

If you use consistent hash to break up the data into multiple BoltDB instances, you could do the same for the Bleve indexes, and then search across them using the IndexAlias feature (described a few times in the google group if you search for it).

**Comment by joeblew99** [comment]
Cheers. Will investigate
