### ISSUE TITLE
Duplicated terms with slightly different spelling

### ISSUE THREAD

**Issue by bep** [blevesearch/bleve#334]
I'm pretty sure this isn't a thing on my end, but I don't understand it.

I have a Tag with a Name, indexed with 

```
	keywordFieldMapping := bleve.NewTextFieldMapping()
	keywordFieldMapping.Analyzer = keyword_analyzer.Name
```

I query for facets for `Tag.Name`, and for some letter combinations, the facet doesn't return what I expect, i.e. `say` becomes `sai`.

I can do a search for both variants and get the same matches, so they are both in the index, but only one shows up in the facets.

**Comment by mschoch** [comment]
"say" becomes "sai" when going through the English analyzer.  The most likely explanation of the behavior you're describing is a problem with the mapping.  So, even though you think you're using the keyword analyzer, you're not.

Also, when you say "you can do a search for both variants and get the same matches" that doesn't imply that both are indexed, because we apply analysis to the search terms as well, so if the English analyzer is being used at search time, searches for both "say" and "sai" will return the same results.

The best thing I can recommend is to share your mapping.

**Comment by bep** [comment]
You are absolutely correct, and thanks for the quick response.

I had to create a subdocument mapping for the tags:

```
	tagsMapping := bleve.NewDocumentMapping()
	tagsMapping.DefaultAnalyzer = keyword_analyzer.Name
	mainMapping.AddSubDocumentMapping("Tags", tagsMapping)
```

And now it all makes sense.
