### ISSUE TITLE
request loading of KV pairs from a file for In-Memory

### ISSUE THREAD

**Issue by noypi** [blevesearch/bleve#344]
Requesting a way, so we can load KV pairs from a file for In-memory use.
Thanks,

example usage:
```
func main(){
    udcq := make(chan upside_down.UpsideDownCouchRow, 1)
    ...
     index, err := bleve.NewUsing("", 
                         bleve.NewIndexMapping(),
                         bleve.Config.DefaultIndexType, 
                         bleve.Config.DefaultKVStore, 
                         map[string]interface{}{
                               "kvsource": udcq,
                         })
}
```

we can add code that does something like:
```
func (udc *UpsideDownCouch) Open() (err error) {
....
....
	if "" == udc.path {
		if kvsource, has := udc.storeConfig["kvsource"]; has {
			var kvwriter store.KVWriter
			kvwriter, err = udc.store.Writer()
			if err != nil {
				return
			}
			kvwriterBatch := kvwriter.NewBatch()
			for kvmem := range kvsource.(chan UpsideDownCouchRow) {
				kvwriterBatch.Set(kvmem.Key(), kvmem.Value())
			}
			err = kvwriter.ExecuteBatch(kvwriterBatch)
			if nil != err {
				return
			}
		}

	}

	// start a reader to look at the index
	var kvreader store.KVReader
	kvreader, err = udc.store.Reader()
	if err != nil {
		return
	}
```

will also need to modify:
```
func newIndexUsing(path string, mapping *IndexMapping, indexType string, kvstore string, kvconfig map[string]interface{}) (*indexImpl, error) {
```

**Comment by mschoch** [comment]
I think what you're trying to do is already possible today, but I'm not exactly sure.  Can you describe what functionality you want and why?

**Comment by noypi** [comment]
@mschoch i plan to deploy an app with blevesearch with appengine; i try to avoid using datastore, and thought gtreap would be working with appengine.

before that, i needed to create the database offline in a KV file. and will load the file to Bleve once an appengine instance is created. 

thanks.

**Comment by mschoch** [comment]
Thanks for explaining the idea.  I've been unsuccessful in the past because all of the KV stores use unsafe in various places.  But I think you're on to something that should work.

The good news is I don't think we need any new APIs to make this work.  And if you get it working it would be awesome to share with the rest of the google group, as I think many people would be interested in hosting small indexes this way.

Here is how I think it can be done today.  We're going to take advantage of the Advanced() method, which is an escape valve we put in to allow direct access to the underlying index/kvstore.  Basically there would be 2 stages, one to export the raw k/v pairs from a running in-memory index, and another one to import k/v pairs.  The following is just pseudo-code but should give you an idea:

```
func ExportBleveGtreap(i *Index) {
    _, kvstore, err := i.Advanced()
    if kvstore, ok := kvstore.(*gtreap.Store); ok {
        // get a snapshot of the root of the treap
            kvstore.m.Lock()
            t := kvstore.t
            kvstore.m.Unlock()

            t.VisitAscend(&gtreap.Item{}, func(i Item) bool {
                if i, ok := i.(*gtreap.Item); ok {
                  // your code to export i.k and i.v
                }
            })
    }
}

func ImportBleveGtreap(i *Index) {
    _, kvstore, err := i.Advanced()
    if kvstore, ok := kvstore.(*gtreap.Store); ok {
        // hold a lock while we insert
            kvstore.m.Lock()
            defer kvstore.m.Unlock()

            for k,v := range ...your data to insert... {
                kvstore.t = kvstore.t.Upsert(&gtreap.Item{k: k, v: v}, rand.Int())
            }
    }
}
```

Let me know if you run into any problems with this approach.

**Comment by noypi** [comment]
I was doing something like this (must work when exporting other KV store also).

```
func ExportBleveGtreap(i *Index) {
....
	var dumpChan chan interface{}
	dumpChan = i.DumpAll()

	kvlist := new(kvutil.KvListPb)
	for c := range dumpChan {
		row := c.(upside_down.UpsideDownCouchRow)
		kvlist.Add(row.Key(), row.Value())
	}

	kvlist.Serialize("./bin/temp.data")

}
```

import creates a new index.
```
func ImportBleveGtreap() (index bleve.Index) {

	udcq := make(chan upside_down.UpsideDownCouchRow, 1)
	list, err := kvutil.Load("./bin/temp.data")
	if nil != err {
		log.Fatal(err)
	}
	go func() {
		for _, kvpb := range list.List {
			kv, err := upside_down.ParseFromKeyValue(kvpb.GetK(), kvpb.GetV())
			if nil != err {
				log.Fatal(err)
			}
			udcq <- kv
		}
		close(udcq)
	}()

	index, err := bleve.NewUsing("", bleve.NewIndexMapping(), bleve.Config.DefaultIndexType, bleve.Config.DefaultKVStore, map[string]interface{}{
		"kvsource": udcq,
	})
	if nil != err {
		log.Fatal(err)
	}
	defer index.Close()
   ....
}
```

**Comment by mschoch** [comment]
OK, so you're approach provides a KV store independent way of exporting the data.  That seems fine.

But, loading the data is going to be KV dependent, as our Index interface has no API to set raw KV pairs.  The approach I described for loading should still work just fine when combined with your means for exporting it.

What about this idea.  What if we created a new KV store type in the "blevex" repo that was designed just for this google app engine use case.  That way, instead of modifying the existing KV stores to know about "kvsource", it becomes a wrapper or decorator around another KV Store.  Does this sound right to you?

I like the idea of the channel of rows for loading too, as it means users could choose their own serialization format, and or handle splitting across multiple files, etc.  But it might be nice to also have a working default implementation.  Do you have one you can share?

**Comment by noypi** [comment]
sounds like can save me some loading time, and i love to have those savings. =)  

yes, i am using this `github.com/noypi/kvutil`.  this may not run smoothly with large files.

thank you very much.

**Comment by mschoch** [comment]
I've cleaned this up a little bit and packaged it up into the "preload" KV store wrapper in the blevex package: https://github.com/blevesearch/blevex/tree/master/preload

In short, you can build the bleve_export command and use it to export any bleve index into the export format.  The export format is a gzipped sequence of KV pairs using protobuf.

When opening a KV store of type `preload` you define which actual KV store to use, and point a path to the file produced by bleve_export.  We then open it, stream in the KV pairs, and load them into the KV store before opening.

See the README in that folder for more info.
