### ISSUE TITLE
Not getting expected search results because of partial matches

### ISSUE THREAD

**Issue by hydrajump** [blevesearch/bleve#350]
Hi I've put together a minimal example showing the issue I'm having with the actual bleve search results not being what I expect.

All my queries are "field specific" and out of ~30 test queries I'm only have trouble with the ones that are similar to those in my example below.

For instance, when I query the `Fruits` field for `pear` I want to match that term exactly, but the actual results show that `pear` is matching `something pear`. The same issue happens when I query `Veges` for `lemon` and it matches `special-lemon`.

What can I do to get the expected results?

```
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/blevesearch/bleve"
)

type Shop struct {
	Name   string   `json:"name"`
	Fruits []string `json:"fruits"`
	Veges  []string `json:"veges"`
	ID     string   `json:"id"`
}

func main() {
	// remove existing bleve index
	os.RemoveAll("example.bleve")

	// open a new index
	mapping := bleve.NewIndexMapping()
	index, err := bleve.New("example.bleve", mapping)
	if err != nil {
		log.Fatal(err)
	}

	// some data
	data1 := Shop{
		Name:   "Shop A",
		Fruits: []string{"Apple", "Something Pear", "Banana"},
		Veges:  []string{"Cucumber", "Lemon", "Carrot"},
		ID:     "shop-a",
	}
	data2 := Shop{
		Name:   "Shop B",
		Fruits: []string{"Pear", "Banana"},
		Veges:  []string{"Cucumber", "Special-Lemon"},
		ID:     "shop-b",
	}

	// index some data
	index.Index(data1.ID, data1)
	index.Index(data2.ID, data2)

	// search 1
	q := bleve.NewQueryStringQuery(`+fruits:"pear" +veges:"cucumber"`)
	req := bleve.NewSearchRequest(q)
	res, err := index.Search(req)
	if err != nil {
		log.Fatal(err)
	}

	// actual results
	// 2 matches:
	//    shop-a
	//    shop-b
	//
	// expected results
	// 1 match:
	//    shop-b
	fmt.Println(res)

	// search 2
	q2 := bleve.NewQueryStringQuery(`+veges:"special-lemon"`)
	req2 := bleve.NewSearchRequest(q2)
	res2, err := index.Search(req2)
	if err != nil {
		log.Fatal(err)
	}

	// actual results
	// 1 matches:
	//    shop-b
	//
	// expected results
	// 1 match:
	//    shop-b
	fmt.Println(res2)

	// search 3
	q3 := bleve.NewQueryStringQuery(`+veges:"lemon"`)
	req3 := bleve.NewSearchRequest(q3)
	res3, err := index.Search(req3)
	if err != nil {
		log.Fatal(err)
	}

	// actual results
	// 2 matches:
	//    shop-a
	//    shop-b
	//
	// expected results
	// 1 match:
	//    shop-a
	fmt.Println(res3)
}
```

**Comment by mschoch** [comment]
The issue is that if you only want to get exact matches, you need an
analyzer that doesn't do any tokenization.  Right now the default analyzer
is splitting 'Special-Lemon' into two terms 'special' and 'lemon',
'Something Pear" into 'something' and 'pear'.  That is why the searches
you're running match those terms.

I thought at first you could use the built-in 'keyword' analyzer, but that
leaves the input terms with upper-case letters, and from the expected
results you provided, you still want to ignore case.  So, to do exactly
what you want, we need to build a custom analyzer.  The code below
demonstrates how to do this, and use it in your IndexMapping.

// build mapping
mapping := bleve.NewIndexMapping()

// build custom analyzer
err := mapping.AddCustomAnalyzer("exactMatchIgnoreCase",
map[string]interface{}{
"type":      custom_analyzer.Name,
"tokenizer": single_token.Name,
"token_filters": []string{
lower_case_filter.Name,
},
})
if err != nil {
log.Fatal(err)
}

// make our custom analyzer the default
mapping.DefaultAnalyzer = "exactMatchIgnoreCase"

When I put this at the top of your example code the searches produce the
results you wanted.

marty

**Comment by hydrajump** [comment]
@mschoch thank you for your help and solution. I've implemented the custom analyser and tested it with my data and it works great!
