### ISSUE TITLE
search: .From bug

### ISSUE THREAD

**Issue by yields** [blevesearch/bleve#378]
Haven't looked into this too too much but i think the bug is [here](https://github.com/blevesearch/bleve/blob/105626269cf398e9de7c2ffeac0cfa1cf60c2f2b/search/collectors/collector_top_score.go#L42), `k: k` should be `k: k + skip` or something.

cheers

**Comment by mschoch** [comment]
You have not described a bug, you have just pointed to a line of code you think is wrong.  I have reviewed it and it looks correct to me, and we have unit tests for this function that are passing.  Please provide more information.

**Comment by yields** [comment]
I see, sorry about that, i should have provided a sample of what i'm talking about:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"strconv"

	"github.com/blevesearch/bleve"
)

type Tweet struct {
	Text string
}

func main() {
	os.RemoveAll("test.index")

	m := bleve.NewIndexMapping()
	i, err := bleve.New("test.index", m)
	if err != nil {
		log.Fatal(err)
	}

	for n := 0; n < 10; n++ {
		err = i.Index(strconv.Itoa(n), Tweet{
			Text: fmt.Sprintf("doc #%d", n+1),
		})
		if err != nil {
			log.Fatal(err)
		}
	}

	query := bleve.NewMatchAllQuery()
	req := bleve.NewSearchRequest(query)
	req.Fields = []string{"*"}
	req.From = 0
	req.Size = 5

	a, err := i.Search(req)
	if err != nil {
		log.Fatal(err)
	}

	req = bleve.NewSearchRequest(query)
	req.Fields = []string{"*"}
	req.From = 5
	req.Size = 5
	b, err := i.Search(req)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("0-5", text(a))
	fmt.Println("5-10", text(b))
}

func text(resp *bleve.SearchResult) (ids []string) {
	for _, doc := range resp.Hits {
		ids = append(ids, doc.Fields["Text"].(string))
	}
	return
}
```

```
// bleve (master)
0-5 [doc #6 doc #5 doc #4 doc #3 doc #2]
5-10 [doc #5 doc #4 doc #3 doc #2 doc #1]

// bleve (v0.2.0)
0-5 [doc #10 doc #9 doc #8 doc #7 doc #6]
5-10 [doc #5 doc #4 doc #3 doc #2 doc #1]
```

As you can see, the code is the same, the output is completely different, am i doing something wrong?

**Comment by mschoch** [comment]
Yep, so this exposes a larger problem.  If you notice, the difference in behavior is in the first 5 results returned, not the second 5.  Also, in your test case all the documents have the same score.  So the real issue is, if you ask for the top 5 docs first, and 10 docs have the same score, which 5 should you get?

Currently bleve only sorts the results on score, this means there is really no guarantee as to which 5 you'll get.  Before this optimization:

https://github.com/blevesearch/bleve/commit/f2aba116c49ea51b27bc9afd3bf15305ef04883c

we got behavior that was more suitable for paging.  I'm not 100% sure it is always going to work either, because its still not enforcing any secondary sort beyond the score.  Its more that it behaves more like a stable sort and doesn't disrupt an order that happens to already be there.

So, the old version clearly works better for pagination, but the new version is faster if you only want to the top N.

Probably the right fix is to roll back the change, and instead move it to a new collector, one that doesn't support skip, and give a name that better describes what it does.  But I'd like to think about it first and run it by a few other people to get their input as well.

**Comment by mschoch** [comment]
Actually, I was thinking about it some more.  I think its possible to keep this optimization without losing the properties we had before.  I think we just have to flip some of the logic around.

**Comment by yields** [comment]
thanks!
