### ISSUE TITLE
where is this store indexed data ?

### ISSUE THREAD

**Issue by bachvtuan** [blevesearch/bleve#379]
Hi, I searched around and see there is no document mention about where data is stored .
Can you tell me about the storage path ?
And now can I backup and restore ?

Thank you !

**Comment by mschoch** [comment]
The path passed to bleve.New() is used to create a directory.
Inside this directory there will be one metadata file index_meta.json.
Also inside this directory there will a file/folder named "store".  The reason I say file/folder is that it depends which KV store implementation is being used.  The default is BoltDB, which will create a single file.  However, if you opt to use LevelDB or one of the other LSM-based solutions, they will create a directory and store multiple files inside of it.

Also, since we support many different KV stores, the story for backup is also mixed.  Many KV stores do not support concurrent access to the database from another process.  In those cases you'll need to use the Advanced() method on bleve, do type-assertion to get access to the underlying KV store and use the backup methods provided by the KV store directly.

This is something we may address in future versions of bleve.

**Comment by bachvtuan** [comment]
Thank you for feedback quickly.
