### ISSUE TITLE
IDF and Merging of Search Results

### ISSUE THREAD

**Issue by emil2k** [blevesearch/bleve#412]
I'm doing a `MultiSearch` across several indices, but merging of search results does not work so well because of the `IDF` factor which depends on the particular index.

I want to add a patch that improves the merging of search results by adjusting the `IDF` factor to be computed using `maxDocs` and `docFreq` across all indices being searched.

@mschoch In your opinion, what would be the best approach to accomplish this? 
I'm willing to give the patch a try, just looking for some guidance.

**Comment by mschoch** [comment]
Yes this will be a great enhancement to Bleve.  The overall complexity isn't high, but it will need to touch a lot of interfaces.

The first thing I would do is to create an interface suitable for describing what ES calls a "search type".  Then, the existing multi-search behavior would become the first implementation, lets call it "simple" for now, since it doesn't map directly to any of the ES strategies.  Next, your implementation would also implement this interface.  The one you're interested in sounds like the DFS, Query, then Fetch approach:  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html

So at this very top-level, users could choose which search type they want by selecting the appropriate implementation.

Next, looking closer at your new implementation will work there are a few things.

1.  How will you get the doc count for each shard?  Straightforward with existing API.
2.  How will you get the term frequencies?  Not as straightfoward, but possible with existing API.  Would need to scan through TermDict.  Probably should add new API to directly look up a set of terms in one call.
3.  But, both 1 and 2 gloss over what appears to be the bigger issue.   How will you even know which terms you need to look up?  Right now the Query/Searcher interfaces that the MultiSearch code will see hide the details of the actual search.  It might be tempting to just add a method which sort of recursively walks the tree and returns the terms needed, but there is still another deeper problem.  Some of the queries like Fuzzy/Regexp/Wildcard/NumericRange/DateRange need to look into the index just to figure out which terms they will later search on.  So, this makes me think it might be cleaner to have a whole new way of executing Searcher instances.  The idea would be sort of like a "dry run" mode, where they don't do the actual search, but report back on what they would have done.  I'll let you explore this deeper, but that is my initial thought.
4.  Finally, I think there is one final big problem.  Once you have the global doc count and term frequencies, how do you pass that down through the stack, so that it will be used instead of the local ones for scoring?  Probably again we want to introduce an interface which allows us to substitute different implementations.  This change will be really important though as we're already looking at how to make scoring more pluggable, and I see this as overlapping with that somewhat.

Those are the issues I see up front and some ideas to think about.  It'd be great if after digging into it a bit more you report back on what interface changes you think make sense.  A change of this scope always needs a little bit of back and forth to get it in good shape.

**Comment by emil2k** [comment]
Thanks for the thoughtful response. I'll need to get better accustomed with the code base, but I'll try to come up with a plan for this patch.
