### ISSUE TITLE
make creating in-memory only indexes more obvious

### ISSUE THREAD

**Issue by mschoch** [blevesearch/bleve#427]
Currently, the way to create a new in-memory only index is to pass "" as the first argument to New, like:

```
index, err := bleve.New("", NewIndexMapping())
```

I received feedback from @a-little-srdjan a few weeks back that this was neither obvious, nor very clear to people later reading the code.  At the time had proposed a new method to create in-memory only indexes.

I'm a bit reluctant to add a new method for this as it seems a bit wasteful to me.  But I agree that it is not obvious, and many users have asked this question (most recently from @AlexanderDaw on gitter).

My proposal is to add a constant to the bleve package, like:

```
const InMemory = ""
```

Then the code to create a new in-memory index would look like:

```
index, err := bleve.New(bleve.InMemory, NewIndexMapping())
```

I think this does address the issue of code readability, but I'm willing to consider other ideas.

Thoughts?

**Comment by daschl** [comment]
I don't know if this is a common go idiom or so, but in general I think there is one case where the application would break (keep working!) in a very problematic way: consider that someone is loading the filepath from some kind of storage and because of an error it is casted/initialized into an empty string. Now what I'd expect is the app failing fast telling me woops there is no path. But in this case the app would boot fine and even accept requests, noone would notice that its actually ephemeral. You'd find out on the next reboot.

Also I don't know how discoverable the constant is (lets say compared to an optional argument).

In terms of what to propose I am not sure to be honest, but since this quite subtly alters behavior I wouldn't be opposed to a new method that makes the behavior explicit. Or `New` is refactored that instead of taking a filepath it accepts some wrapper object that could in the future also carry more config information and would also indicate if peristence should be disabled?

**Comment by mschoch** [comment]
Thanks, for the feedback.  I think there are valid points to both sides.

My initial thinking was that since the empty string is zero-value for type string, and since the empty string is obviously not a valid path, that this was an acceptable way to represent the desire to build an in-memory index.

However, I am persuaded by the argument that if you ever accidentally created an in-memory index, the results are disastrous.  Sure, you could always avoid the problem with better error handling, but a large number of bleve bug reports are from people ignoring a returned error.  So there is some evidence that people will find there way into this particular disaster.

By having a separate method signature, you would only end up with an in-memory index when you've specifically written code to create it.  So I will introduce this change in the near future.
