### ISSUE TITLE
DocIDReader Next() documentation seems incorrect

### ISSUE THREAD

**Issue by pmezard** [blevesearch/bleve#501]
Hello,

According to https://github.com/blevesearch/bleve/blob/master/index/index.go#L179

DocIDReader.Next() is supposed to return io.EOF when the enumeration is terminated. It does not seem to be implemented that way in either upsidedown or smolder. The current behaviour is more like:

- Return an error on real error
- Return a non-nil InternalID if the element is valid
- Return a nil InternalID at the end of the sequence

Is that correct ?

**Comment by mschoch** [comment]
Yes, the documentation is incorrect, and the behavior you described sounds right.

But, as we get closer to 1.0, its an opportunity to correct behavior like this if we want.  I personally don't see value in io.EOF (in this case) as it complicates the handling logic a little bit to differentiate real error from end of stream.  But, if people feel strongly otherwise I'd like to hear that.

**Comment by pmezard** [comment]
The current behaviour seems fine.

Are you fixing it or do you want a PR?

**Comment by mschoch** [comment]
I can do it later this week, or if you want to send PR I can merge sooner.

**Comment by pmezard** [comment]
Here you go https://github.com/blevesearch/bleve/pull/502

**Comment by mschoch** [comment]
Merged, Thanks.
