### ISSUE TITLE
any way to get all struct field when search matched?

### ISSUE THREAD

**Issue by saggit** [blevesearch/bleve#507]
Hi, I try the example, it works great, but the searchResult seems only contains the document id,

is there any way to display the search result like elastic?

**Comment by mschoch** [comment]
There isn't a built-in way to store the entire original document, but you can store individual field values (they are stored by default).  To get them included in the search result, you should set the Fields property of the SearchRequest.  It is an array of field names that you want loaded along with the search result.  Also, you use a special field name "*" to request that all the stored fields be returned.

**Comment by saggit** [comment]
Thank you very much for you quick reply and help, it works.

**Comment by vandanaramesh14** [comment]
How do I request for all Fields to be searched, but the match results to be displayed in only the fields which have hits?

**Comment by mschoch** [comment]
@vandanaramesh14 please open new issues for questions like this, rather than commenting on already closed issues.

1.  The "fields" capability returns all the stored fields you asked for, it has no knowledge of which fields were related to matching.
2.  The "highlight' feature will do what you want.  It figures out which fields had matches, and automatically performs result highlighting on them.
3.  If highlight doesn't do what you want, there is another feature which is disabled by default.  You can set `IncludeLocations` to `true` in the SearchRequest.  This will return to the exact locations of all matches.  It makes the SearchResult much larger, which is why it is disabled by default, but it could be used to figure out which fields you want to show.

**Comment by vandanaramesh14** [comment]
Thank you.
