### ISSUE TITLE
N-gram tokenizer

### ISSUE THREAD

**Issue by minagawa-sho** [blevesearch/bleve#516]
I want to analyze the Japanese text by bi-gram tokenizing.
(e.g. "こんにちは。" → "こん" "んに" "にち" "ちは" "は。")
Japanese is not the language whose text is not delimited with space, so the analyzing like that is very effective for Japanese text indexing.
Is there good idea to solve with Bleve library ?

**Comment by mschoch** [comment]
Bleve has two options for working with Japanese text.

1)  We offer a "cjk" analyzer which uses a simple bi-gram like the one you described.

You can test it out here: http://analysis.blevesearch.com/analysis

When I input your example text, and select "cjk", I get:

Position	Term	Start	End
1	こん	0	6
2	んに	3	9
3	にち	6	12
4	ちは	9	15

All analyzers in Bleve are built by combining several components.  So, if this doesn't produce exactly the output you want, you can probably reuse some of the pieces to build something that does.

2)  The other approach we offer is the "ja" analyzer which uses the kagome library for tokenization.

This analyzer is not a part of the bleve core because it includes a large dictionary.  You can find this analyzer here:

https://github.com/blevesearch/blevex/tree/master/lang/ja

**Comment by minagawa-sho** [comment]
It's amazing !
The first option matches my want, thanks.
