### ISSUE TITLE
Support the context package

### ISSUE THREAD

**Issue by gmlewis** [blevesearch/bleve#549]
It would be nice if `bleve` supported the `context` package, so you could coordinate cancellation across many different goroutines.

It's now available in the standard library as https://golang.org/pkg/context/.

[go-github](https://github.com/google/go-github) recently went through this exercise in https://github.com/google/go-github/issues/526

**Comment by mschoch** [comment]
We do support context, so that you can cancel search requests, with the SearchInContext method.  We use the older import `golang.org/x/net/context` because we supported this before it was brought into the standard library.

We will switch to "context" at some point, but we need to require 1.7+ when we make that change.

**Comment by gmlewis** [comment]
Excellent!  Thank you for the information, @mschoch!
Feel free to close.
