### ISSUE TITLE
integration with other databases?

### ISSUE THREAD

**Issue by leeola** [blevesearch/bleve#580]
I'm curious, is there any sane method to allow bleve to index for another
database?

Eg, Lets say you're in need of query features that go a bit beyond what Bleve appears to offer. SQL-like features. So you use a simple database that doesn't have full text
search but *does* have SQL-like features.

Is there a sane way to integrate FTS from Bleve with this other db? Perhaps having Bleve filter results based on it's FTS?

**Comment by mschoch** [comment]
I think most use of bleve follows this pattern to some degree.  You should use something else as your primary data store, and use bleve to build an index for full-text search purposes.

If you want to use bleve to filter results that already satisfied some other external query, you can restrict the matches to IDs satisfying the other query with a DocIDQuery.

So, as an example, let's say you run query like: `comments > 50 AND contains(description, "golang")`

Let's assume you're using a SQL database as your primary store, and your SQL database doesn't actually have a `contains` full-text search operator.

Then you can first run `comments > 50` in your SQL database, get those doc ids, and now run a bleve search:

```
Conjuncts:
  - DocIdQuery [ list of doc ids]
  - MatchQuery "golang"
```

This solution has scalability issues, and I wouldn't recommend it if you have millions ids satisfying the first query, but works pretty-well otherwise.

**Comment by leeola** [comment]
Appreciate it! I wouldn't have thought performance of that would be sufficient for the majority of cases. Eg, hundreds/a-couple-fewthousands of results.

**Comment by mschoch** [comment]
Well, I tested around a thousand I think, but tens of thousands is probably where it starts to break down.  In the end, everyone has different requirements, so it probably won't be good enough for everyone.

Ultimately, at some point you need deeper integration between your query planner and the index to really solve the problem.

In the future we'll offer a non-scoring, non-ordering streaming mode from bleve, which is what many systems would prefer to integrate with.  But, this would only be for integration with other systems and wouldn't be very useful on its own.
