### ISSUE TITLE
Any way to determine which subdocuments for hit locations?

### ISSUE THREAD

**Issue by caseymrm** [blevesearch/bleve#596]
Hello, thank you for Bleve!

When using IncludeLocations and sub-documents, I haven't been able to find a way to determine which sub-document the Hit.Location applies to (or more generally which sub-document(s) triggered the hit, which could be useful to know even when not using locations).

Here's a contrived example: https://play.golang.org/p/-QKGWUQkfO

When run, it produces:

```
Field Emails.Subject = [horse cat monkey apple pear banana]
Field Id = thread1
Field Emails.Id = [email1 email2]
    Field Emails.Subject has term cat from 6 to 9 (Pos 2?)
```

What I'd like to know is that "cat" was found in the Subject of "email1", not "email2".

Currently the only way I see to do it is to go back and look at each Subject myself, checking positions 6-9 until I find which email has a matching Subject.

Based on the way Emails.Subject contains the subjects concatenated, I don't have high hopes that the data on which sub-document is accessible when constructing the Location, but since the returned positions are relative to the original strings I thought I'd double-check.

Thanks for any insights!

**Comment by mschoch** [comment]
The Location structure has one additional field called `ArrayLocations` which contains the information you're looking for.  It is an array of values since there could be multiple arrays in an arbitrary path through the JSON, and this records the position within each.

Notice that when you search for `cat` it has the value 0, and if you change the search to `pear` you get the value 1.  This value corresponds to the index within the Emails array.

**Comment by caseymrm** [comment]
Oh great, I completely misunderstood what ```ArrayLocations``` was.

As long as I'm here, can I ask what ```Pos``` is?

Thanks again!

**Comment by mschoch** [comment]
It's the position of the term within the field, starting at 1 (mostly used for comparing relative positions of terms in a phrase search).
