### ISSUE TITLE
roaring bitmaps

### ISSUE THREAD

**Issue by gedw99** [blevesearch/bleve#619]
i dont knwo enough about low level data structures with bleve, but i came across roaring bitmaps, and was wondering if its useful for bleve ?

I started using https://github.com/pilosa/pilosa
Its basis is  https://github.com/RoaringBitmap/RoaringBitmap

Elastic search uses it and many others....

Sorry about it being such an opened ended question, but well you know how it is - always trying to learn...

**Comment by steveyen** [comment]
Hi @gedw99 -- turns out we're now indeed using roaring bitmaps in bleve, in its latest the 'scorch' indexing engine, which uses roaring bitmaps in how scorch represents postings lists.  Conjunction searches, for example, now leverage the ability in roaring bitmaps to efficiently 'AND' together multiple roaring bitmaps.
