### ISSUE TITLE
Unable to search for "no" using bleve.NewQueryStringQuery()

### ISSUE THREAD

**Issue by GurjitSinghTatla** [blevesearch/bleve#642]
The search results match for words/phrases like "yes","yeah", "nope","not interested" etc. but it does says "No matches found" if I search for "no" even though it is present in the data.

Data:
`{
    "tag":"en-gen-no",
    "phrases": [
        "no",
        "nope",
        "not sure",
        "does not suits me",
        "not interested"
    ]
}`

Code:
`query := bleve.NewMatchPhraseQuery(q)
		req := bleve.NewSearchRequest(query)
		req.Fields = []string{"phrases"}
		searchResults, err := paraphraseIndex.Search(req)
		if err != nil {
			log.Fatal(err)
		}
		if searchResults.Hits.Len() == 0 {
			fmt.Println("No matches found")
		} else {
			for i := 0; i < searchResults.Hits.Len(); {
				hit := searchResults.Hits[i]
				fmt.Printf("%s\n", hit.Fields["phrases"])
				i = i + 1
			}
		}`

**Comment by mschoch** [comment]
The reason is that `no` is in the English stop word list:

https://github.com/blevesearch/bleve/blob/master/analysis/lang/en/stop_words_en.go#L279

You didn't mention which analyzer you're using, but the default would be `standard` and this analyzer removes English stop words:

https://github.com/blevesearch/bleve/blob/master/analysis/analyzer/standard/standard.go#L44

You'll need to define a custom analyzer that does not remove English stop words (or define a custom stopwords list) if you want to be able to search for the word `no`.

**Comment by gurjit1** [comment]
I assumed I can use Keyword or Simple Analyzers as docs say they don't do stopwords removal. But the results don't change.
Am I assuming wrong or should either Analyzer work?

**Comment by mschoch** [comment]
The simple analyzer should work.  Can you share the code?  Unfortunately there are many subtle issues with mappings and the code that uses them that can introduce problems.

The keyword analyzer will work for finding "no", but wouldn't work for phases like "not interested" because it would index them as a single token.

**Comment by gurjit1** [comment]
There was some issue in my code it works fine with simple analyzer
