### ISSUE TITLE
Search result in JSON format

### ISSUE THREAD

**Issue by mysticmode** [blevesearch/bleve#646]
I'm trying to implement bleve into https://libreread.org

I couldn't find any docs for getting the result in json format. I checked the code here
https://github.com/blevesearch/bleve/blob/master/search.go#L435

The result comes only in the formatted string. Could someone guide me here?

Thanks,
Nirmal

**Comment by mschoch** [comment]
Bleve is just a Go library, it doesn't know anything about serialization formats like JSON.  Search results are returned as Go structure.  If you're referring to the stored fields, they are returned in a form that aproximates (but is not exactly) the original value.  Text fields come back as a string, numeric fields come back as a float, dates come back as a string (but not necessarily in the original format), and geo points come back as slice [lon, lat].  If any field had multiple values (due to slices in the original, you will get a slice back.  However, there is no way to reproduce the original structure, all Bleve knows about is the flat list of fields that were placed into the index.

You have 2 choices:

1)  Your application knows the original structure, so you take the flat list of stored field values and recreate the structure yourself.

2)  Use the internal storage mechanism to store the original JSON for each document.  Then whenever you get a hit, you pull that hit's key out of internal storage.  NOTE: this is supported for now, but some of our new indexing schemes may make this approach not work well in the future.

**Comment by mysticmode** [comment]
Thank you!
