### ISSUE TITLE
Q: handling unpredictable schema

### ISSUE THREAD

**Issue by ivanjaros** [blevesearch/bleve#718]
Hi,
I have a use case where each object can and will have completely different fields(and data types). So I cannot create schema that the search server can use to index this data in advance.

With elasticsearch I would have to create basically new index for every object which would be a nightmare, or translate each field into flat key/value structure and have a global index of these without a lot of features that would be otherwise available(facets, range search..).

Can bleve handle such use case?

**Comment by mschoch** [comment]
The mapping capabilities in bleve are heavily based on ES (earlier versions), so you're likely to encounter the same limitations.

Bleve does handle mixed data types in the same field a bit differently than ES.  We allow one document to index a string and another in the same field (provided you have mappings that dictate doing this).  Unfortunately, this isn't particularly useful in practice and often leads to problems at query time.

I've generally been in favor of moving towards what current ES does, which is to get rid of types entirely and recommend using separate indexes for separate types.  My way of thinking about it is that while your data may be schemaless, different fields, and different types within fields with the same name, but when building an index, you generally want to impose more structure.  If I have JSON documents, some have a "category" field that is a string, and others have a "category" field that is an array of numbers.  It's just easier to think about this as one field in JSON that happens to be two separate fields in the index.  This doesn't mean you have to expose that detail to your end users, it just means the operation of bleve is more sane, because you can explicitly work with something concrete.  The complexity and failings of bleve today are mostly in the areas where we do "detection" and "automatically" select behaviors, with rules about "inheritance".  All of this logic is tempting to write, but in the end it never does exactly what you want, and you're better off keeping it simple and explicit, even if that means more code in the application.

The reality is that bleve is a flat index of fields, and for sanity you're better off only sticking a single type of data in that field.  Code that changes/hides this detail is better off in the application as it's not really as generic as it seems.
