### ISSUE TITLE
Stop-word token filter does not update positions

### ISSUE THREAD

**Issue by ethantkoenig** [blevesearch/bleve#735]
The `StopTokensFilter` does not update positions when it drops tokens. For instance,

`[{term="eat", pos=0}, {term="the", pos=1}, {term="watermelon", pos=2}]`

will be filtered to

`[{term="eat", pos=0}, {term="watermelon", pos=2}]`

instead of

`[{term="eat", pos=0}, {term="watermelon", pos=1}]`

I'm not very familiar with the codebase, but I assume that TokenFilters should emit output with successive positions (e.g. this is what the `CamelCaseFilter` does, see #615)?

**Comment by mschoch** [comment]
It's not as simple as just emitting successive positions, because there are filters like n-gram that have to emit multiple tokens in the same position.  Not updating the positions is typically fine, because phrase search still works since the analyzer at search time also removes the stop words and has the same relative offsets.

Regarding CamelCaseFilter, it was contributed externally, and the change was suggested by someone else, but approved by the original external contributor.  I don't use it or know if it's really behaving like the other filters.

Are you having a problem with the current behavior?

**Comment by ethantkoenig** [comment]
I'm not having a problem, but asked to better understand the expected behavior of token filters with respect to token positions.

Also, I previously updated the CamelCaseFilter to emit tokens with positions (#615), and currently it emits successive positions, regardless of the positions of the input tokens, e.g.

`[{term="i", pos=2}, {term="amACamel", pos=3"}, {term="indeed", pos=4}]` is filtered to
`[{term="i", pos=1}, {term="am", pos=2}, {term="A", pos=3}, {term="Camel", pos=4}, {term="indeed", pos=5}]`.

If this is incorrect, please let me know if I will fix the CamelCaseFilter accordingly.
