### ISSUE TITLE
how do I get the matched documents when using indexAlias

### ISSUE THREAD

**Issue by krystollia** [blevesearch/bleve#797]
Hi, I used indexAlias to hold documents, I searched from the indexAlias, but failed to get the documents by docID, here is the code:
```
index1, _ := bleve.Open("path1")
index2, _ := bleve.Open("path2")
indexAlias := bleve.NewIndexAlias(index1, index2)
indexAlias.Index("docID11", doc)

query := bleve.NewMatchQuery("term111")
result, _ := indexAlias.Search(query)

for _, hit := range result.Hits {
    doc, err := indexAlias.Document(hit.ID) // here an error said "cannot perform single index operation on multiple index alias"
}
```

It seems not supported to search documents using indexAlias with multiple indexes? If so, what is indexAlias designed for, only for switching between different indexes?

@mschoch @steveyen thanks

**Comment by mschoch** [comment]
You are correct, the IndexAlias does not have functionality to retrieve individual documents.  The reason is that we wanted to keep it focused on just the scatter/gather of searches across all indexes in the alias.  If we were to implement it there are 2 issues, first with the existing API, we don't know which index actually has the document, so we have to scatter/gather the request to load the document, second we'd have to handle the case that multiple indexes claim to have the document, and again the existing API doesn't support that well.

There are 2 choices:

1.  You can request the stored fields be returned in the initial query (set Fields to []string{"*"} in your SearchRequest)
2.  You can look at each hit, there is a field called Index which is type string.  This has the name associated with each Index in the alias (you can override the name, but it defaults to the path).  Based on the name, you can go back directly to that index, and then use the Document() method directly.

**Comment by krystollia** [comment]
Clear. Thanks @mschoch
