### ISSUE TITLE
[Store] akrylysov/pogreb: Embedded key-value store for read-heavy workloads written in Go

### ISSUE THREAD

**Issue by nsuper** [blevesearch/bleve#819]
https://github.com/akrylysov/pogreb
- 100% Go.
- Optimized for fast random lookups and infrequent bulk inserts.
- Can store larger-than-memory data sets.
- Low memory usage.
- All DB methods are safe for concurrent use by multiple goroutines.

![read-benchmark](http://akrylysov.github.io/pogreb/read-bench.png)

**Comment by ivanjaros** [comment]
That graph is total BS. Badger is gazzilion times faster than bolt, yet bolt is waaay above badger. Nope, note buying it.

**Comment by steveyen** [comment]
Hi @nsuper -- thanks for the link.  Unfortunately, looks like the API supported by https://github.com/akrylysov/pogreb might not be powerful enough to be used by bleve (and bleve's "upsidedown" indexing engine).  Specifically, ordered iteration of a range of keys looks to be missing from pogreb (since pogreb seems to be a hash based approach).
