### ISSUE TITLE
Add ASCII Folding Filter

### ISSUE THREAD

**Issue by protheusfr** [blevesearch/bleve#957]
Hello, 

I've search in documentation and in source code but not found the response.
My goal is to allow bleve to to retrieve documents that contain (for example) : 
- Belvédère
- belvédère
- belvedere
- belvedère 
- Belvedere 

with the same score through a string query like "belvedere".
I've use to_lower token_filter to manage case but found nothing to remove / ignore accents.

Any idea ?

**Comment by mschoch** [comment]
To do this in a general way we need a filter that does ASCII folding.  We don't have such a filter today, though some of the language specific analyzers include a filter which folds specific accent characters likely to appear in a particular language.

**Comment by Funzinator** [comment]
I have ported (and modified) [Lucene's ASCIIFoldingFilter](https://lucene.apache.org/core/4_0_0/analyzers-common/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html) for my bleve project.
The one difference is that German umlauts ä, ö, ü fold to ae, oe, ue instead of a, e, u but that would be easily changed back.
You can find it at [Funzinator/bleve-toolkit/index/filter/asciifolding/asciifolding.go](https://github.com/Funzinator/bleve-toolkit/blob/master/index/filter/asciifolding/asciifolding.go).

I would also be happy to create a PR for the bleve project if you are interested.

**Comment by Tom29** [comment]
@Funzinator It simply converts accented character to non-accented character?
I don't think this is a good approach for searching.
It would be sort by accented word to. Like:

While search for Belvédère
1. Belvédère
2. Belvedere

Search for Belvedere
1. Belvedere
2. Belvédère

**Comment by Funzinator** [comment]
The filter is applied before the data is stored in the index. Therefore `Belvédère` is stored as `Belvedere`.
The same filter is applied to the input when searching (analyzed). If you search for `Belvédère` it will be converted to `Belvedere`. I don't understand why it would make a difference if you search for `Belvédère` or `Belvedere` since both trigger a search for `Belvedere` after the filter has been applied.

**Comment by steveyen** [comment]
One thought (haven't tried it), is if the amount of folding is limited, maybe one or more regexp char filters that replace characters with ASCII versions might do the trick.  Again, haven't tried it.

**Comment by mschoch** [comment]
@Funzinator I think PR would be welcome addition to the project.  Lots of users ask for ASCII folding.
